'use strict';
const assert=require('node:assert/strict');
const d=require('../src/core/pos-domain.js');

const order=d.createOrder({orderType:'Delivery',customerName:'Ali',customerPhone:'0300',deliveryAddress:'Main Street',items:[{id:'p1',name:'Pizza',price:100,qty:2}],tax:20,deliveryFee:30},'cashier');
assert.equal(order.totalCents,25000);
assert.equal(order.stage,'draft');
d.transition(order,'confirmed','cashier');
d.transition(order,'routed','cashier');
d.transition(order,'preparing','kitchen');
d.transition(order,'ready','kitchen');
d.transition(order,'delivery','dispatch');
let p=d.addPayment(order,{method:'Cash',amount:250},'cashier');
assert.equal(p.remainingCents,0); assert.equal(order.stage,'settled');
d.transition(order,'completed','cashier');
assert.throws(()=>d.transition(order,'preparing'),/Cannot move/);
const job=d.createPrintJob(order,'delivery');
assert.equal(job.status,'queued'); assert.equal(job.printer,'Thermal Printer');
const tpl=d.createReceiptTemplate({theme:'modern',paperWidth:80});
assert.equal(tpl.paperWidth,80); assert.equal(tpl.theme,'modern');
const rendered=d.renderTemplate('{{business}}\n{{order_id}}\n{{items}}\nTOTAL {{total}}',order,{business:'MK Foods'});
assert.match(rendered,/MK Foods/); assert.match(rendered,/Pizza/); assert.match(rendered,/250/);
const products=[{id:'p1',stock:5}]; const next=d.allocateInventory(order,products); assert.equal(next[0].stock,3); assert.equal(products[0].stock,5);
assert.throws(()=>d.createOrder({orderType:'Delivery',items:[{id:'p',name:'x',price:1,qty:1}]}),/Delivery address is required/);
console.log('MK Foods unified POS domain tests passed');
