const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');

const banking = read('src/renderer/banking.js');
const production = read('src/renderer/production.js');
const workflowUi = read('src/renderer/order-workflow.js');
const printManager = read('src/renderer/print-manager.js');
const printers = read('src/renderer/printers.js');
const tauri = read('src/renderer/tauri.js');
const index = read('src/renderer/index.html');
const pkg = JSON.parse(read('package.json'));
const tauriConfig = JSON.parse(read('src-tauri/tauri.conf.json'));
const cargoText = read('src-tauri/Cargo.toml');
const workflow = read('.github/workflows/build-windows.yml');
const windowsBuild = read('build-windows.bat');
const windowsPowerShell = read('build-windows.ps1');
const rustPrinter = read('src-tauri/src/printer.rs');

function assert(ok, msg) { if (!ok) throw new Error(msg); }

assert(index.includes('banking.js'), 'Banking screen is not loaded');
assert(index.includes('production.js'), 'Production safeguards are not loaded');
assert(index.includes('order-workflow.js'), 'Staged order workflow is not loaded');
assert(index.includes('print-manager.js'), 'Print Manager is not loaded');
assert(banking.includes('paymentMerchantId'), 'Bank merchant configuration missing');
assert(banking.includes('paymentEnvironment'), 'Bank environment configuration missing');
assert(production.includes('pending_verification'), 'Digital payments must not be auto-settled');
assert(production.includes('bankReady'), 'Digital payment readiness guard missing');
assert(/tax\s*=\s*taxable\s*\*\s*taxRate\s*\/\s*100/.test(production), 'Checkout tax calculation missing');
assert(/taxable\s*=\s*Math\.max\(0\s*,\s*subtotal\s*-\s*discount\)/.test(production), 'Checkout taxable amount calculation missing');
assert(/taxRate\s*=\s*Math\.max\(0\s*,\s*num\(db\?\.settings\?\.tax\)\)/.test(production), 'Checkout tax rate configuration missing');
assert(production.includes('deliveryFee'), 'Delivery fee calculation missing');
assert(production.includes('Not enough stock'), 'Checkout stock guard missing');
assert(production.includes('posTotals'), 'POS subtotal/tax/total display missing');
assert(production.includes('customerId'), 'Customer must be attached to a sale when selected');
assert(production.includes('tableId'), 'Table assignment must be retained on a sale');
assert(production.includes('counterId'), 'Counter assignment must be retained on a sale');
assert(production.includes('cashCollectedBy'), 'Cashier responsibility must be retained on a sale');
assert(!production.includes('cardNumber') && !production.includes('cvv'), 'Card PAN/CVV must not be stored in renderer');
assert(workflowUi.includes('collectedBy'), 'Order collector tracking missing');
assert(workflowUi.includes('preparedBy'), 'Order preparer tracking missing');
assert(workflowUi.includes('readyBy'), 'Kitchen ready tracking missing');
assert(workflowUi.includes('cashCollectedBy'), 'Cash collector tracking missing');
assert(workflowUi.includes('Shake Kitchen'), 'Shake kitchen routing missing');
assert(workflowUi.includes('Biryani Kitchen'), 'Biryani kitchen routing missing');
assert(workflowUi.includes('Fastfood Kitchen'), 'Fastfood kitchen routing missing');
assert(workflowUi.includes('assignments'), 'Per-kitchen assignment tracking missing');
assert(workflowUi.includes('showOrderTracking'), 'Order tracking UI missing');
assert(workflowUi.includes('queueReceipt'), 'Workflow must queue receipts instead of opening print windows');
assert(!workflowUi.includes("window.open('','_blank'"), 'Order workflow must not open receipt popups');
assert(printManager.includes('window.print()'), 'Print Manager must retain the system print action');
assert(printManager.includes('queueOrderForPrint'), 'Print Manager queue bridge missing');
assert(!printManager.includes("window.open('','_blank'"), 'Print Manager must not open receipt popups');
assert(tauri.includes('discoverPrinters'), 'Printer discovery bridge missing');
assert(tauri.includes('connectPrinter'), 'Printer connection bridge missing');
assert(printers.includes('Every discovered Bluetooth device is selectable'), 'Bluetooth devices must remain clickable');
assert(printers.includes('Direct Bluetooth'), 'Bluetooth direct transport fallback missing');
assert(printers.includes('Windows queue'), 'Windows printer queue fallback missing');
assert(printers.includes('findWindowsFallback'), 'Windows queue matching fallback missing');
assert(rustPrinter.includes('Get-CimInstance Win32_PnPEntity'), 'Bluetooth PnP fallback discovery missing');
assert(rustPrinter.includes('BTHENUM*'), 'BTHENUM device discovery missing');
assert(rustPrinter.includes('bluetooth_mac_from_instance'), 'Bluetooth MAC extraction missing');
assert(pkg.version === tauriConfig.version, 'Package version must match Tauri application version');
assert(pkg.version === '2.2.0', 'Application release version must be 2.2.0');
assert(cargoText.match(/version\s*=\s*"([^"]+)"/)[1] === pkg.version, 'Cargo package version must match application version');
assert(workflow.includes('npm test'), 'Windows build must run automated tests');
assert(!workflow.includes('cache: npm'), 'Windows build must not require a lockfile just to configure npm cache');
assert(windowsBuild.includes('build-windows.ps1'), 'Windows launcher must call the PowerShell build');
assert(windowsPowerShell.includes('Microsoft Visual Studio\\Installer\\vswhere.exe'), 'PowerShell build must detect Visual Studio');
assert(windowsPowerShell.includes('Find-VisualStudio'), 'PowerShell build must have Visual Studio discovery');
assert(windowsPowerShell.includes('Activate-DirectMsvc'), 'PowerShell build must have direct MSVC activation');
assert(windowsPowerShell.includes('vcvarsall.bat'), 'PowerShell build must have vcvarsall fallback');
assert(windowsPowerShell.includes('VsDevCmd.bat'), 'PowerShell build must have VsDevCmd fallback');
assert(windowsPowerShell.includes('Try-BatchMsvc'), 'PowerShell build must automatically try fallback activation');
assert(windowsPowerShell.includes('aarch64-pc-windows-msvc'), 'Windows build must keep ARM64 target support');
assert(windowsPowerShell.includes('i686-pc-windows-msvc'), 'Windows build must keep x86 target support');

console.log('Production safety, printer connectivity, version consistency, staged workflow, non-popup printing, and Windows build checks passed.');
