const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const index = read('src/renderer/index.html');
const banking = read('src/renderer/banking.js');
const printers = read('src/renderer/printers.js');
const printerNative = read('src-tauri/src/printer.rs');
const printManager = read('src/renderer/print-manager.js');
const enterpriseUi = read('src/renderer/enterprise-ui.js');
const worldClass = read('src/renderer/world-class-pos.js');
const layoutFixes = read('src/renderer/layout-fixes.css');
const dialogFree = read('src/renderer/dialog-free-legacy.js');
const loginWarning = fs.existsSync(path.join(root,'src/renderer/login-warning.js')) ? read('src/renderer/login-warning.js') : '';
const pkg = JSON.parse(read('package.json'));

assert(index.includes('./banking.js'), 'banking.js must be loaded');
assert(index.includes('data-view="banking"'), 'Banking navigation must exist');
assert(index.includes('data-view="printmanager"'), 'Print Manager navigation must exist');
assert(index.includes('./print-manager.js'), 'print-manager.js must be loaded');
assert(index.includes('./layout-fixes.css'), 'Layout hardening CSS must be loaded');
assert(index.includes('./dialog-free-legacy.js'), 'Popup-free legacy action layer must be loaded');
assert(!index.includes('./login-warning.js'), 'Native login alert hook must not be loaded');
assert(banking.includes('Raast P2M / 1LINK'), 'Raast/1LINK provider option must exist');
assert(banking.includes('Bank Transfer / Raast'), 'Bank tender must exist');
assert(printers.includes('discoverBluetooth'), 'Native Bluetooth discovery bridge must exist');
assert(!printers.includes('navigator.bluetooth'), 'Browser Bluetooth picker must not be used');
assert(!printers.includes('navigator.serial'), 'Browser serial picker must not be used');
assert(printerNative.includes('__BLUETOOTH_DISCOVER__'), 'Native Bluetooth discovery command must exist');
assert(printerNative.includes('Get-PnpDevice') && printerNative.includes('BTHENUM*'), 'Windows Bluetooth inventory must be native');
assert(printerNative.includes('Win32_PnPEntity'), 'Windows PnP fallback inventory must exist');
assert(printerNative.includes('EnumPrintersW'), 'Windows printer enumeration must use the spooler');
assert(printerNative.includes('WritePrinter'), 'Windows thermal printing must use RAW spooler output');
assert(/window\.printReceipt\s*=\s*order\s*=>\s*\{\s*queue\(order\)\s*;\s*go\(['"]printmanager['"]\)\s*;\s*\}/.test(printManager), 'Receipt printing must queue into Print Manager');
assert(printManager.includes('addManualPrintOrder'), 'Manual print orders must be supported');
assert(printManager.includes('removePrintOrder'), 'Print jobs must be removable');
assert(printManager.includes('Pass / Print'), 'Print jobs must be passable to printing');
assert(!printManager.includes("alert(`${o.id}"), 'Print order details must not use an order-detail popup');
assert(enterpriseUi.includes('enhanceNav'), 'Enterprise navigation enhancement must exist');
assert(worldClass.includes('wc-shell'), 'World-class POS workspace must exist');
assert(layoutFixes.includes('body:has(.wc-shell) #nav'), 'Duplicate sidebar prevention must exist');
assert(dialogFree.includes('window.deleteProduct'), 'Popup-free delete action must exist');
assert(dialogFree.includes('window.dispatchOrder'), 'Popup-free dispatch action must exist');
assert(!loginWarning.includes('nativeAlert'), 'Native alert implementation must not remain active');
assert(typeof pkg.scripts.test === 'string', 'npm test script must exist');
console.log('MK Foods renderer/native smoke tests passed');
