const fs = require('fs');
const path = require('path');
const cp = require('child_process');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const workflowPath = path.join(root, 'src/renderer/order-workflow.js');
const workflow = read('src/renderer/order-workflow.js');
const compat = read('src/renderer/workflow-compat.js');
const customerHistory = read('src/renderer/customer-history.js');
const index = read('src/renderer/index.html');
const contract = `${workflow}\n${compat}`;
function assert(ok, msg) { if (!ok) throw new Error(msg); }
cp.execFileSync(process.execPath, ['--check', workflowPath], { stdio: 'inherit' });
cp.execFileSync(process.execPath, ['--check', path.join(root, 'src/renderer/workflow-compat.js')], { stdio: 'inherit' });
cp.execFileSync(process.execPath, ['--check', path.join(root, 'src/renderer/customer-history.js')], { stdio: 'inherit' });
assert(index.includes('auth-ui.js'), 'Authentication UI is not loaded');
assert(index.includes('workflow-session.js'), 'Workflow session bridge is not loaded');
assert(index.includes('order-workflow.js'), 'Order workflow script is not loaded');
assert(index.includes('workflow-compat.js'), 'Workflow compatibility layer is not loaded');
assert(index.includes('customer-history.js'), 'Customer history module is not loaded');
for (const key of ['collectOrder','forwardKitchen','markPrepared','markCooked','markReady','sendToCounter','collectCash','showOrderTracking']) assert(contract.includes(`window.${key}`), `${key} method missing`);
for (const key of ['collectedBy','preparedBy','cookedBy','cashCollectedBy']) assert(contract.includes(key), `${key} tracking missing`);
for (const key of ['Shake Kitchen','Biryani Kitchen','Fastfood Kitchen']) assert(contract.includes(key), `${key} routing missing`);
assert(contract.includes('Sale Receipt') || contract.includes('SALE RECEIPT'), 'Final sale receipt missing');
assert(customerHistory.includes('function customerHistorySearch') && customerHistory.includes('window.customerHistorySearch'), 'Customer history search missing');
assert(customerHistory.includes('showCustomerHistory'), 'Customer history display missing');
console.log('Staged order workflow tests passed.');
