#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::{collections::HashMap,fs,path::PathBuf,sync::Mutex,time::{SystemTime,UNIX_EPOCH}};
use pbkdf2::pbkdf2_hmac; use rand::{rngs::OsRng,RngCore}; use serde_json::{json,Value}; use sha2::Sha256; use subtle::ConstantTimeEq; use tauri::{Manager,State,WebviewWindow};
const ITER:u32=210000; const SESSION_MS:u128=30*60*1000;
struct Session{user:Value,last:u128} struct AppState{file:PathBuf,db:Value,sessions:HashMap<String,Session>}
fn now()->u128{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis()}
fn hash(s:&str)->String{let mut salt=[0u8;16];OsRng.fill_bytes(&mut salt);let mut key=[0u8;32];pbkdf2_hmac::<Sha256>(s.as_bytes(),&salt,ITER,&mut key);format!("pbkdf2${}${}${}",ITER,hex::encode(salt),hex::encode(key))}
fn verify(s:&str,h:&str)->bool{let p:Vec<_>=h.split('$').collect();if p.len()!=4||p[0]!="pbkdf2"{return false}let it=p[1].parse().unwrap_or(0);let salt=match hex::decode(p[2]){Ok(x)=>x,Err(_)=>return false};let exp=match hex::decode(p[3]){Ok(x)=>x,Err(_)=>return false};let mut out=vec![0u8;exp.len()];pbkdf2_hmac::<Sha256>(s.as_bytes(),&salt,it,&mut out);out.as_slice().ct_eq(exp.as_slice()).into()}
fn arr<'a>(db:&'a mut Value,k:&str)->&'a mut Vec<Value>{if !db[k].is_array(){db[k]=json!([])}db[k].as_array_mut().unwrap()}
fn persist(s:&AppState)->Result<(),String>{if let Some(p)=s.file.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}fs::write(&s.file,serde_json::to_string_pretty(&s.db).map_err(|e|e.to_string())?).map_err(|e|e.to_string())}
fn audit(s:&mut AppState,a:&str,d:Value)->Result<(),String>{let mut e=json!({"at":chrono::Utc::now().to_rfc3339(),"action":a});if let(Some(x),Some(y))=(e.as_object_mut(),d.as_object()){for(k,v)in y{x.insert(k.clone(),v.clone());}}arr(&mut s.db,"audit").push(e);persist(s)}
fn seed()->Value{let u=|n:&str,r:&str|json!({"username":n,"role":r,"passwordHash":hash("0099"),"pinHash":hash("0099"),"failedAttempts":0,"lockedUntil":null,"passwordChangedAt":null,"active":true});json!({"version":5,"authVersion":2,"users":[u("admin","Admin"),u("owner","Owner"),u("cashier","Cashier"),u("accountant","Accountant")],"staff":[],"counters":[],"products":[{"id":"p1","name":"Chicken Pizza","category":"Pizza","price":850,"cost":500,"stock":50,"minStock":5,"available":true},{"id":"p2","name":"Cheese Pizza","category":"Pizza","price":750,"cost":430,"stock":50,"minStock":5,"available":true},{"id":"p3","name":"Zinger Burger","category":"Burgers","price":550,"cost":280,"stock":50,"minStock":5,"available":true},{"id":"p4","name":"Fries","category":"Sides","price":220,"cost":90,"stock":80,"minStock":10,"available":true},{"id":"p5","name":"Soft Drink","category":"Drinks","price":120,"cost":50,"stock":100,"minStock":15,"available":true},{"id":"p6","name":"Ice Cream","category":"Desserts","price":250,"cost":100,"stock":40,"minStock":5,"available":true}],"orders":[],"customers":[],"riders":[],"tables":[{"id":"T1","name":"T1","capacity":4,"status":"Open"},{"id":"T2","name":"T2","capacity":4,"status":"Open"},{"id":"T3","name":"T3","capacity":4,"status":"Open"},{"id":"T4","name":"T4","capacity":4,"status":"Open"}],"kitchenTickets":[],"expenses":[],"suppliers":[],"purchaseOrders":[],"stockMovements":[],"cashEntries":[],"shifts":[],"audit":[],"settings":{"business":"MK Pizza & Ice Bar","address":"Collage Road Abbas Chowk, Bhakkar, Pakistan","phone":"0316 9700025","currency":"Rs.","tax":0,"printerMac":"","printerName":"","riderBaseFare":100,"riderPerKm":25,"lowStockThreshold":5}})}
fn migrate(db:&mut Value){for k in ["users","staff","counters","products","orders","customers","riders","tables","kitchenTickets","expenses","suppliers","purchaseOrders","stockMovements","cashEntries","shifts","audit"]{if !db[k].is_array(){db[k]=json!([])}}if !db["settings"].is_object(){db["settings"]=json!({})}for(k,v)in json!({"riderBaseFare":100,"riderPerKm":25,"lowStockThreshold":5,"tax":0,"currency":"Rs.","printerName":"","printerMac":""}).as_object().unwrap(){db["settings"].as_object_mut().unwrap().entry(k.clone()).or_insert(v.clone());}if let Some(ps)=db["products"].as_array_mut(){for p in ps{if p["stock"].is_null(){p["stock"]=json!(0)}if p["cost"].is_null(){p["cost"]=json!(0)}if p["minStock"].is_null(){p["minStock"]=json!(5)}}}if let Some(us)=db["users"].as_array_mut(){for u in us{if !u["passwordHash"].as_str().unwrap_or("").starts_with("pbkdf2$"){u["passwordHash"]=json!(hash("0099"));u["passwordChangedAt"]=Value::Null}if u["failedAttempts"].is_null(){u["failedAttempts"]=json!(0)}if u["lockedUntil"].is_null(){u["lockedUntil"]=Value::Null}if u["pinHash"].is_null(){u["pinHash"]=Value::Null}if u["active"].is_null(){u["active"]=json!(true)}}}db["version"]=json!(5)}
fn load(file:PathBuf)->AppState{let mut db=fs::read_to_string(&file).ok().and_then(|x|serde_json::from_str(&x).ok()).unwrap_or_else(seed);migrate(&mut db);let s=AppState{file,db,sessions:HashMap::new()};let _=persist(&s);s}
fn user(u:&Value)->Value{json!({"username":u["username"],"role":u["role"]})}
fn find<'a>(db:&'a mut Value,n:&str)->Option<&'a mut Value>{db["users"].as_array_mut()?.iter_mut().find(|u|u["username"].as_str().unwrap_or("").eq_ignore_ascii_case(n.trim()))}
fn ensure(s:&mut AppState,w:&WebviewWindow,roles:Option<&[&str]>)->Result<Value,String>{let label=w.label().to_string();let expired=match s.sessions.get(&label){Some(x)=>now().saturating_sub(x.last)>SESSION_MS,None=>true};if expired{s.sessions.remove(&label);return Err("UNAUTHENTICATED".into())}let u=s.sessions.get_mut(&label).unwrap();u.last=now();if let Some(rs)=roles{if !rs.contains(&u.user["role"].as_str().unwrap_or("")){return Err("FORBIDDEN".into())}}Ok(u.user.clone())}
fn auth(s:&mut AppState,w:&WebviewWindow,n:&str,p:&str,pin:bool)->Result<Value,String>{let name=n.trim().to_lowercase();let (ok,locked,retry,view,change)={let u=find(&mut s.db,&name).ok_or("INVALID")?;if u["active"].as_bool()==Some(false){return Ok(json!({"ok":false,"reason":"INACTIVE"}))}let lock=u["lockedUntil"].as_str().and_then(|x|chrono::DateTime::parse_from_rfc3339(x).ok()).map(|d|d.timestamp_millis()as u128>now()).unwrap_or(false);let field=if pin{"pinHash"}else{"passwordHash"};(verify(p,u[field].as_str().unwrap_or("")),lock,u["lockedUntil"].clone(),user(u),u["passwordChangedAt"].is_null())};if locked{return Ok(json!({"ok":false,"reason":"LOCKED","retryAt":retry}))}if !ok{let mut lock=false;if let Some(u)=find(&mut s.db,&name){let a=u["failedAttempts"].as_u64().unwrap_or(0)+1;if a>=5{u["failedAttempts"]=json!(0);u["lockedUntil"]=json!((chrono::Utc::now()+chrono::Duration::minutes(15)).to_rfc3339());lock=true}else{u["failedAttempts"]=json!(a)}}if lock{audit(s,"ACCOUNT_LOCKED",json!({"username":name}))?}else{persist(s)?}return Ok(json!({"ok":false,"reason":"INVALID"}))}if let Some(u)=find(&mut s.db,&name){u["failedAttempts"]=json!(0);u["lockedUntil"]=Value::Null}audit(s,"LOGIN",json!({"username":name,"method":if pin{"pin"}else{"password"}}))?;s.sessions.insert(w.label().to_string(),Session{user:view.clone(),last:now()});Ok(json!({"ok":true,"user":view,"mustChange":change}))}
#[tauri::command]fn app_info(s:State<Mutex<AppState>>)->Result<Value,String>{let x=s.lock().unwrap();Ok(json!({"name":"MK Foods POS","business":x.db["settings"]["business"],"mode":"offline-first","version":env!("CARGO_PKG_VERSION")}))}
#[tauri::command]fn login(w:WebviewWindow,s:State<Mutex<AppState>>,u:String,p:String)->Result<Value,String>{auth(&mut s.lock().unwrap(),&w,&u,&p,false)}
#[tauri::command]fn pin_login(w:WebviewWindow,s:State<Mutex<AppState>>,u:String,p:String)->Result<Value,String>{auth(&mut s.lock().unwrap(),&w,&u,&p,true)}
#[tauri::command]fn logout(w:WebviewWindow,s:State<Mutex<AppState>>)->Result<Value,String>{s.lock().unwrap().sessions.remove(w.label());Ok(json!({"ok":true}))}
#[tauri::command]fn session(w:WebviewWindow,s:State<Mutex<AppState>>)->Result<Value,String>{let mut x=s.lock().unwrap();match ensure(&mut x,&w,None){Ok(u)=>Ok(json!({"ok":true,"user":u})),Err(r)=>Ok(json!({"ok":false,"reason":r}))}}
#[tauri::command]fn snapshot(w:WebviewWindow,s:State<Mutex<AppState>>)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,None)?;Ok(x.db.clone())}
#[tauri::command]fn change_password(w:WebviewWindow,s:State<Mutex<AppState>>,current:String,next:String)->Result<Value,String>{let mut x=s.lock().unwrap();let u=ensure(&mut x,&w,None)?;if next.len()<8{return Ok(json!({"ok":false,"reason":"WEAK"}))}let n=u["username"].as_str().unwrap_or("").to_string();if !find(&mut x.db,&n).map(|q|verify(&current,q["passwordHash"].as_str().unwrap_or(""))).unwrap_or(false){return Ok(json!({"ok":false,"reason":"INVALID"}))}if let Some(q)=find(&mut x.db,&n){q["passwordHash"]=json!(hash(&next));q["passwordChangedAt"]=json!(chrono::Utc::now().to_rfc3339())}audit(&mut x,"PASSWORD_CHANGED",json!({"username":n}))?;Ok(json!({"ok":true}))}
#[tauri::command]fn reset_password(w:WebviewWindow,s:State<Mutex<AppState>>,target:String,temp:String)->Result<Value,String>{let mut x=s.lock().unwrap();let a=ensure(&mut x,&w,Some(&["Admin","Owner"]))?;if temp.len()<8{return Ok(json!({"ok":false,"reason":"WEAK"}))}if find(&mut x.db,&target).is_none(){return Ok(json!({"ok":false,"reason":"DENIED"}))}if let Some(q)=find(&mut x.db,&target){q["passwordHash"]=json!(hash(&temp));q["passwordChangedAt"]=Value::Null}audit(&mut x,"PASSWORD_RESET",json!({"admin":a["username"],"username":target}))?;Ok(json!({"ok":true}))}
#[tauri::command]fn create_order(w:WebviewWindow,s:State<Mutex<AppState>>,mut o:Value)->Result<Value,String>{let mut x=s.lock().unwrap();let u=ensure(&mut x,&w,None)?;let id=o["id"].as_str().unwrap_or("").to_string();if id.is_empty(){return Err("ORDER_ID_REQUIRED".into())}let subtotal=o["subtotal"].as_f64().unwrap_or(o["total"].as_f64().unwrap_or(0.0)).max(0.0);let discount=o["discount"].as_f64().unwrap_or(0.0).clamp(0.0,subtotal);let tax=(subtotal-discount).max(0.0)*x.db["settings"]["tax"].as_f64().unwrap_or(0.0)/100.0;let fee=o["deliveryFee"].as_f64().unwrap_or(0.0).max(0.0);o["createdBy"]=u["username"].clone();o["tax"]=json!(o["tax"].as_f64().unwrap_or(tax));o["total"]=json!((subtotal-discount+o["tax"].as_f64().unwrap_or(tax)+fee).max(0.0));o["status"]=json!(o["status"].as_str().unwrap_or("new"));if let Some(items)=o["items"].as_array(){for i in items{let id=i["id"].as_str().unwrap_or("");let q=i["qty"].as_f64().unwrap_or(0.0);if let Some(p)=x.db["products"].as_array_mut().and_then(|a|a.iter_mut().find(|p|p["id"].as_str()==Some(id))){p["stock"]=json!((p["stock"].as_f64().unwrap_or(0.0)-q).max(0.0));if p["stock"].as_f64().unwrap_or(0.0)<=p["minStock"].as_f64().unwrap_or(5.0){p["available"]=json!(false)}}}}arr(&mut x.db,"orders").push(o.clone());arr(&mut x.db,"kitchenTickets").push(json!({"id":format!("K-{}",id),"orderId":id,"status":"new","createdAt":o["createdAt"],"items":o["items"]}));audit(&mut x,"ORDER_CREATED",json!({"id":id,"total":o["total"]}))?;Ok(o)}
#[tauri::command]fn order_status(w:WebviewWindow,s:State<Mutex<AppState>>,id:String,status:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;let mut found=false;for o in arr(&mut x.db,"orders"){if o["id"].as_str()==Some(&id){o["status"]=json!(status.clone());found=true;break}}if !found{return Ok(json!(false))}for k in arr(&mut x.db,"kitchenTickets"){if k["orderId"].as_str()==Some(&id){k["status"]=json!(if status=="completed"{"done"}else{status.as_str()})}}audit(&mut x,"ORDER_STATUS",json!({"id":id,"status":status}))?;Ok(json!(true))}
#[tauri::command]fn assign_order(w:WebviewWindow,s:State<Mutex<AppState>>,id:String,rider:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;let mut found=false;for o in arr(&mut x.db,"orders"){if o["id"].as_str()==Some(&id){o["riderId"]=json!(rider.clone());o["status"]=json!("dispatched");found=true;break}}if !found{return Err("ORDER_NOT_FOUND".into())}for r in arr(&mut x.db,"riders"){if r["id"].as_str()==Some(&rider){r["status"]=json!("Assigned")}}audit(&mut x,"ORDER_DISPATCHED",json!({"orderId":id,"riderId":rider}))?;Ok(json!(true))}
#[tauri::command]fn update_table(w:WebviewWindow,s:State<Mutex<AppState>>,id:String,status:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;let mut out=None;for t in arr(&mut x.db,"tables"){if t["id"].as_str()==Some(&id){t["status"]=json!(status.clone());out=Some(t.clone());break}}if let Some(t)=out{audit(&mut x,"TABLE_STATUS",json!({"id":id,"status":status}))?;return Ok(t)}Ok(json!(false))}
#[tauri::command]fn pos_action(w:WebviewWindow,s:State<Mutex<AppState>>,op:String,data:Value)->Result<Value,String>{let mut x=s.lock().unwrap();match op.as_str(){
"add_customer"=>{ensure(&mut x,&w,None)?;let id=format!("c-{}",now());let v=json!({"id":id,"name":data["name"],"phone":data["phone"].as_str().unwrap_or(""),"email":data["email"].as_str().unwrap_or(""),"birthday":data["birthday"].as_str().unwrap_or(""),"points":data["points"].as_f64().unwrap_or(0.0)});arr(&mut x.db,"customers").push(v.clone());audit(&mut x,"CUSTOMER_CREATED",json!({"id":id}))?;Ok(v)}
"add_rider"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let v=json!({"id":format!("r-{}",now()),"name":data["name"],"phone":data["phone"],"zone":data["zone"],"status":"Available","customPerKm":data["customPerKm"].as_f64().unwrap_or(0.0)});arr(&mut x.db,"riders").push(v.clone());audit(&mut x,"RIDER_CREATED",json!({"id":v["id"]}))?;Ok(v)}
"rider_rate"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;x.db["settings"]["riderBaseFare"]=json!(data["base"].as_f64().unwrap_or(0.0).max(0.0));x.db["settings"]["riderPerKm"]=json!(data["perKm"].as_f64().unwrap_or(0.0).max(0.0));audit(&mut x,"RIDER_RATE_UPDATED",data.clone())?;Ok(x.db["settings"].clone())}
"calc_delivery"=>{ensure(&mut x,&w,None)?;let mut per=x.db["settings"]["riderPerKm"].as_f64().unwrap_or(25.0);if let Some(r)=x.db["riders"].as_array().and_then(|a|a.iter().find(|r|r["id"].as_str()==data["riderId"].as_str())){if r["customPerKm"].as_f64().unwrap_or(0.0)>0.0{per=r["customPerKm"].as_f64().unwrap()}}let base=x.db["settings"]["riderBaseFare"].as_f64().unwrap_or(100.0);Ok(json!({"base":base,"perKm":per,"riderPay":base+data["distanceKm"].as_f64().unwrap_or(0.0).max(0.0)*per}))}
"delivery"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;let id=data["orderId"].as_str().unwrap_or("");let mut out=false;for o in arr(&mut x.db,"orders"){if o["id"].as_str()==Some(id){for k in ["riderId","distanceKm","deliveryFee","riderPay","address","zone","status"]{if !data[k].is_null(){o[k]=data[k].clone()}}out=true;break}}if out{audit(&mut x,"DELIVERY_UPDATED",json!({"orderId":id}))?;Ok(json!(true))}else{Err("ORDER_NOT_FOUND".into())}}
"add_staff"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let u=data["username"].as_str().unwrap_or("").trim().to_lowercase();if u.is_empty(){return Err("USERNAME_REQUIRED".into())}if x.db["users"].as_array().unwrap().iter().any(|q|q["username"].as_str()==Some(&u)){return Err("USERNAME_EXISTS".into())}let role=data["role"].as_str().unwrap_or("Cashier");let pass=data["password"].as_str().filter(|p|p.len()>=8).unwrap_or("0099");let v=json!({"id":format!("st-{}",now()),"name":data["name"],"username":u,"role":role,"phone":data["phone"],"salary":data["salary"].as_f64().unwrap_or(0.0),"active":true,"joinedAt":chrono::Utc::now().to_rfc3339()});arr(&mut x.db,"staff").push(v.clone());arr(&mut x.db,"users").push(json!({"username":u,"role":role,"passwordHash":hash(pass),"pinHash":hash(data["pin"].as_str().unwrap_or("0099")),"failedAttempts":0,"lockedUntil":null,"passwordChangedAt":null,"active":true}));audit(&mut x,"STAFF_CREATED",json!({"id":v["id"]}))?;Ok(v)}
"update_staff"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let id=data["id"].as_str().unwrap_or("");let mut uname=None;for q in arr(&mut x.db,"staff"){if q["id"].as_str()==Some(id){for(k,v)in data.as_object().unwrap(){if k!="id"{q[k]=v.clone()}}uname=q["username"].as_str().map(str::to_string);break}}if let Some(n)=uname{if let Some(u)=find(&mut x.db,&n){if let Some(r)=data["role"].as_str(){u["role"]=json!(r)}}}audit(&mut x,"STAFF_UPDATED",json!({"id":id}))?;Ok(json!(true))}
"deactivate_staff"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let id=data["id"].as_str().unwrap_or("");let mut n=None;for q in arr(&mut x.db,"staff"){if q["id"].as_str()==Some(id){q["active"]=json!(false);n=q["username"].as_str().map(str::to_string);break}}if let Some(u)=n{if let Some(q)=find(&mut x.db,&u){q["active"]=json!(false)}}audit(&mut x,"STAFF_DEACTIVATED",json!({"id":id}))?;Ok(json!(true))}
"add_counter"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let v=json!({"id":format!("ctr-{}",now()),"name":data["name"],"code":data["code"],"assignedUser":data["assignedUser"],"active":true});arr(&mut x.db,"counters").push(v.clone());audit(&mut x,"COUNTER_CREATED",json!({"id":v["id"]}))?;Ok(v)}
"update_counter"=>{ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let id=data["id"].as_str().unwrap_or("");let mut out=None;for q in arr(&mut x.db,"counters"){if q["id"].as_str()==Some(id){for(k,v)in data.as_object().unwrap(){if k!="id"{q[k]=v.clone()}}out=Some(q.clone());break}}if let Some(v)=out{audit(&mut x,"COUNTER_UPDATED",json!({"id":id}))?;Ok(v)}else{Ok(json!(false))}}
"add_expense"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;let amount=data["amount"].as_f64().unwrap_or(0.0);if amount<=0.0{return Err("AMOUNT_REQUIRED".into())}let v=json!({"id":format!("exp-{}",now()),"date":data["date"],"category":data["category"],"amount":amount,"payment":data["payment"],"note":data["note"],"staff":data["staff"]});arr(&mut x.db,"expenses").push(v.clone());audit(&mut x,"EXPENSE_CREATED",json!({"id":v["id"],"amount":amount}))?;Ok(v)}
"delete_expense"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;arr(&mut x.db,"expenses").retain(|q|q["id"].as_str()!=data["id"].as_str());audit(&mut x,"EXPENSE_DELETED",json!({"id":data["id"]}))?;Ok(json!(true))}
"stock_adjust"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;let id=data["productId"].as_str().unwrap_or("");let q=data["qty"].as_f64().unwrap_or(0.0);let mut out=None;let mut before=0.0;for p in arr(&mut x.db,"products"){if p["id"].as_str()==Some(id){before=p["stock"].as_f64().unwrap_or(0.0);p["stock"]=json!((before+q).max(0.0));p["available"]=json!(p["stock"].as_f64().unwrap_or(0.0)>0.0);out=Some(p.clone());break}}if let Some(v)=out{arr(&mut x.db,"stockMovements").push(json!({"id":format!("sm-{}",now()),"productId":id,"qty":q,"before":before,"after":v["stock"],"reason":data["reason"]}));audit(&mut x,"STOCK_ADJUSTED",json!({"productId":id,"qty":q}))?;Ok(v)}else{Err("PRODUCT_NOT_FOUND".into())}}
"add_supplier"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;let v=json!({"id":format!("sup-{}",now()),"name":data["name"],"phone":data["phone"],"address":data["address"],"balance":data["balance"].as_f64().unwrap_or(0.0)});arr(&mut x.db,"suppliers").push(v.clone());audit(&mut x,"SUPPLIER_CREATED",json!({"id":v["id"]}))?;Ok(v)}
"add_purchase"=>{ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;let v=json!({"id":format!("po-{}",now()),"supplierId":data["supplierId"],"date":data["date"],"items":data["items"],"total":data["total"],"paid":data["paid"],"status":"Received"});arr(&mut x.db,"purchaseOrders").push(v.clone());if let Some(items)=data["items"].as_array(){for i in items{let id=i["productId"].as_str().unwrap_or("");let q=i["qty"].as_f64().unwrap_or(0.0);let cost=i["cost"].as_f64().unwrap_or(0.0);if let Some(p)=x.db["products"].as_array_mut().and_then(|a|a.iter_mut().find(|p|p["id"].as_str()==Some(id))){p["stock"]=json!(p["stock"].as_f64().unwrap_or(0.0)+q);p["cost"]=json!(cost)}}}audit(&mut x,"PURCHASE_RECEIVED",json!({"id":v["id"]}))?;Ok(v)}
_=>Err("UNKNOWN_OPERATION".into())}}
#[tauri::command]fn save_product(w:WebviewWindow,s:State<Mutex<AppState>>,p:Value)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let id=p["id"].as_str().filter(|z|!z.is_empty()).map(str::to_string).unwrap_or_else(||format!("p-{}",now()));let v=json!({"id":id,"name":p["name"],"category":p["category"],"price":p["price"].as_f64().unwrap_or(0.0),"cost":p["cost"].as_f64().unwrap_or(0.0),"stock":p["stock"].as_f64().unwrap_or(0.0),"minStock":p["minStock"].as_f64().unwrap_or(5.0),"available":p["available"].as_bool().unwrap_or(true)});let mut upd=false;for q in arr(&mut x.db,"products"){if q["id"].as_str()==Some(&id){*q=v.clone();upd=true;break}}if !upd{arr(&mut x.db,"products").push(v.clone())}audit(&mut x,if upd{"MENU_UPDATED"}else{"MENU_CREATED"},json!({"id":id}))?;Ok(v)}
#[tauri::command]fn delete_product(w:WebviewWindow,s:State<Mutex<AppState>>,id:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner"]))?;arr(&mut x.db,"products").retain(|q|q["id"].as_str()!=Some(&id));audit(&mut x,"MENU_DELETED",json!({"id":id}))?;Ok(json!(true))}
#[tauri::command]fn update_settings(w:WebviewWindow,s:State<Mutex<AppState>>,settings:Value)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner"]))?;for(k,v)in settings.as_object().unwrap(){x.db["settings"][k]=v.clone()}persist(&x)?;Ok(x.db["settings"].clone())}
#[tauri::command]fn replace_products(w:WebviewWindow,s:State<Mutex<AppState>>,products:Vec<Value>)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner"]))?;x.db["products"]=json!(products);persist(&x)?;Ok(x.db["products"].clone())}
#[tauri::command]fn add_customer(w:WebviewWindow,s:State<Mutex<AppState>>,c:Value)->Result<Value,String>{pos_action(w,s,"add_customer".into(),c)}
#[tauri::command]fn add_rider(w:WebviewWindow,s:State<Mutex<AppState>>,r:Value)->Result<Value,String>{pos_action(w,s,"add_rider".into(),r)}
#[tauri::command]fn export_menu(w:WebviewWindow,s:State<Mutex<AppState>>,path:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Accountant"]))?;let mut c="id,name,category,price,cost,stock,minStock,available\n".to_string();for p in x.db["products"].as_array().unwrap(){c+=&format!("{},{},{},{},{},{},{},{}\n",p["id"].as_str().unwrap_or(""),p["name"].as_str().unwrap_or(""),p["category"].as_str().unwrap_or(""),p["price"],p["cost"],p["stock"],p["minStock"],p["available"])}fs::write(&path,c).map_err(|e|e.to_string())?;Ok(json!(path))}
#[tauri::command]fn import_menu(w:WebviewWindow,s:State<Mutex<AppState>>,path:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner"]))?;let text=fs::read_to_string(&path).map_err(|e|e.to_string())?;let mut p=Vec::new();for l in text.lines().skip(1){let a:Vec<_>=l.split(',').collect();if a.len()>=8{p.push(json!({"id":a[0],"name":a[1],"category":a[2],"price":a[3].parse::<f64>().unwrap_or(0.0),"cost":a[4].parse::<f64>().unwrap_or(0.0),"stock":a[5].parse::<f64>().unwrap_or(0.0),"minStock":a[6].parse::<f64>().unwrap_or(5.0),"available":a[7].to_lowercase()!="false"}))}}let count=p.len();x.db["products"]=json!(p);audit(&mut x,"MENU_BULK_IMPORT",json!({"count":count}))?;Ok(json!(count))}
#[tauri::command]fn discover_printers(w:WebviewWindow,s:State<Mutex<AppState>>)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;drop(x);let output=std::process::Command::new("powershell").args(["-NoProfile","-NonInteractive","-Command","Get-Printer | Select-Object Name,Default,PrinterStatus | ConvertTo-Json -Compress"]).output().map_err(|e|format!("PRINTER_DISCOVERY_FAILED: {}",e))?;if !output.status.success(){return Err("PRINTER_DISCOVERY_FAILED".into())}let raw=String::from_utf8_lossy(&output.stdout).trim().to_string();if raw.is_empty(){return Ok(json!([]))}let parsed:Value=serde_json::from_str(&raw).unwrap_or(json!([]));let list=match parsed{Value::Array(a)=>a,Value::Object(o)=>vec![Value::Object(o)],_=>vec![]};Ok(json!(list.into_iter().filter_map(|p|{let name=p["Name"].as_str()?.to_string();Some(json!({"name":name,"default":p["Default"].as_bool().unwrap_or(false),"status":p["PrinterStatus"].as_i64().unwrap_or(0)}))}).collect::<Vec<Value>>()))}
#[tauri::command]fn connect_printer(w:WebviewWindow,s:State<Mutex<AppState>>,name:String)->Result<Value,String>{let mut x=s.lock().unwrap();ensure(&mut x,&w,Some(&["Admin","Owner","Cashier"]))?;x.db["settings"]["printerName"]=json!(name.clone());x.db["settings"]["printerMac"]=Value::Null;persist(&x)?;audit(&mut x,"PRINTER_SELECTED",json!({"printerName":name}))?;Ok(json!(true))}
fn main(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).setup(|app|{let dir=app.path().app_data_dir().map_err(|e|e.to_string())?;app.manage(Mutex::new(load(dir.join("data").join("store.json"))));Ok(())}).invoke_handler(tauri::generate_handler![app_info,login,pin_login,logout,session,snapshot,change_password,reset_password,create_order,order_status,assign_order,update_table,pos_action,save_product,delete_product,update_settings,replace_products,add_customer,add_rider,export_menu,import_menu,discover_printers,connect_printer]).run(tauri::generate_context!()).expect("error while running MK Foods POS");}