const{app,BrowserWindow,ipcMain,dialog}=require('electron');const path=require('path');const fs=require('fs');const{execFile}=require('child_process');const{randomBytes}=require('crypto');const{createStore}=require('./store');let store;const sessions=new Map();const SESSION_MS=30*60*1000;
function bt(command,args=[]){return new Promise(resolve=>execFile(command,args,{timeout:8000},(err,stdout)=>resolve(err?[]:String(stdout).split(/\r?\n/).filter(Boolean))));}
async function discoverPrinters(){if(process.platform==='linux'){const lines=await bt('bluetoothctl',['devices']);return lines.map(x=>{const m=x.match(/^Device\s+([0-9A-F:]{17})\s+(.+)$/i);return m?{mac:m[1],name:m[2]}:null}).filter(Boolean)}if(process.platform==='win32'){const lines=await bt('powershell',['-NoProfile','-Command','Get-PnpDevice -Class Bluetooth | Where-Object {$_.Status -eq "OK"} | Select-Object FriendlyName,InstanceId | ConvertTo-Csv -NoTypeInformation']);return lines.slice(1).map(x=>({name:x.split(',')[0]?.replace(/^"|"$/g,''),mac:(x.match(/([0-9A-F]{2}(?:-[0-9A-F]{2}){5})/i)||[])[1]?.replaceAll('-',':')||''})).filter(x=>x.name)}return[]}
async function autoConnectPrinter(){const s=store.get().settings;if(!s.printerMac)return false;if(process.platform==='linux'){await bt('bluetoothctl',['connect',s.printerMac]);return true}return true}
function login(sender,u,p,type='password'){const r=type==='pin'?store.authenticatePin(u,p):store.authenticate(u,p);if(r.ok){const token=randomBytes(32).toString('hex');sessions.set(sender.id,{token,user:r.user,lastActivity:Date.now()});return{...r,token}}return r}
function requireAuth(sender){const s=sessions.get(sender.id);if(!s)return{ok:false,reason:'UNAUTHENTICATED'};if(Date.now()-s.lastActivity>SESSION_MS){sessions.delete(sender.id);return{ok:false,reason:'SESSION_EXPIRED'}}s.lastActivity=Date.now();return{ok:true,session:s}}
function requireRole(sender,roles){const r=requireAuth(sender);if(!r.ok)return r;if(!roles.includes(r.session.user.role))return{ok:false,reason:'FORBIDDEN'};return r}
function createWindow(){const win=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,backgroundColor:'#f6f7f5',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.loadFile(path.join(__dirname,'renderer','index.html'));win.webContents.on('destroyed',()=>sessions.delete(win.webContents.id))}
app.whenReady().then(async()=>{store=createStore(app.getPath('userData'));await autoConnectPrinter();ipcMain.handle('app:info',()=>({name:'MK Foods POS',business:store.get().settings.business,mode:'offline-first',version:app.getVersion()}));ipcMain.handle('auth:login',(e,u,p)=>login(e.sender,u,p,'password'));ipcMain.handle('auth:pinLogin',(e,u,p)=>login(e.sender,u,p,'pin'));ipcMain.handle('auth:logout',e=>{sessions.delete(e.sender.id);return{ok:true}});ipcMain.handle('auth:changePassword',(e,current,next)=>{const r=requireAuth(e.sender);if(!r.ok)return r;return store.changePassword(r.session.user.username,current,next)});ipcMain.handle('auth:resetPassword',(e,target,temp)=>{const r=requireRole(e.sender,['Admin','Owner']);if(!r.ok)return r;return store.resetPassword(r.session.user.username,target,temp)});ipcMain.handle('auth:session',(e)=>{const r=requireAuth(e.sender);return r.ok?{ok:true,user:r.session.user,expiresIn:Math.max(0,SESSION_MS-(Date.now()-r.session.lastActivity))}:r});
const auth=(roles,fn)=> (e,...args)=>{const r=roles?requireRole(e.sender,roles):requireAuth(e.sender);if(!r.ok)return r;return fn(e,...args,r.session)};
ipcMain.handle('db:snapshot',auth(null,()=>store.get()));ipcMain.handle('orders:create',auth(null,(_,o)=>store.addOrder(o)));ipcMain.handle('orders:status',auth(['Admin','Owner','Cashier'],(_,id,s)=>store.updateOrderStatus(id,s)));ipcMain.handle('orders:assign',auth(['Admin','Owner','Cashier'],(_,id,r)=>store.assignOrder(id,r)));ipcMain.handle('table:update',auth(['Admin','Owner','Cashier'],(_,id,s)=>store.updateTable(id,s)));ipcMain.handle('customer:add',auth(null,(_,c)=>store.addCustomer(c)));ipcMain.handle('rider:add',auth(['Admin','Owner'],(_,r)=>store.addRider(r)));ipcMain.handle('menu:save',auth(['Admin','Owner'],(_,p)=>store.saveProduct(p)));ipcMain.handle('menu:delete',auth(['Admin','Owner'],(_,id)=>store.deleteProduct(id)));ipcMain.handle('menu:replace',auth(['Admin','Owner'],(_,p)=>store.replaceProducts(p)));ipcMain.handle('audit:add',auth(null,(_,e)=>store.addAudit(e)));ipcMain.handle('settings:update',auth(['Admin','Owner'],(_,s)=>store.updateSettings(s)));ipcMain.handle('printer:discover',auth(['Admin','Owner','Cashier'],()=>discoverPrinters()));ipcMain.handle('printer:connect',auth(['Admin','Owner','Cashier'],(_,mac)=>{store.updateSettings({printerMac:mac});return autoConnectPrinter()}));ipcMain.handle('menu:export',auth(['Admin','Owner','Accountant'],async()=>{const r=await dialog.showSaveDialog({defaultPath:'mk-foods-menu.csv',filters:[{name:'CSV',extensions:['csv']}]});if(r.canceled)return null;const rows=store.get().products.map(p=>[p.id,p.name,p.category,p.price,p.available].join(','));fs.writeFileSync(r.filePath,['id,name,category,price,available',...rows].join('\n'));return r.filePath}));ipcMain.handle('menu:import',auth(['Admin','Owner'],async()=>{const r=await dialog.showOpenDialog({properties:['openFile'],filters:[{name:'CSV',extensions:['csv']}]});if(r.canceled)return null;const lines=fs.readFileSync(r.filePaths[0],'utf8').split(/\r?\n/).filter(Boolean);const products=lines.slice(1).map(line=>{const [id,name,category,price,available]=line.split(',');return{id,name,category,price,available}});store.replaceProducts(products);return products.length}));createWindow();app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()})});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});
