let db={};let cart=[];let view='dashboard';let session=null;
const money=n=>`Rs. ${Number(n||0).toLocaleString()}`;
async function load(){db=await window.mkFoods.snapshot();render()}
const canManage=()=>['Admin','Owner'].includes(session?.role);
function shell(title,sub,body,action=''){return `<div class="head"><div><h1>${title}</h1><div class="muted">${sub}</div></div>${action}</div>${body}`}
function render(){const v=document.getElementById('view');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({dashboard,pos,tables,kds,delivery,customers,menu,inventory,suppliers,printers,reports,history,settings}[view]||dashboard)(v)}
function dashboard(v){let sales=db.orders.reduce((s,o)=>s+o.total,0);v.innerHTML=shell('Dashboard','Connected local modules',`<div class="grid cards"><div class="card"><small>Daily Sales</small><strong>${money(sales)}</strong></div><div class="card"><small>Active Orders</small><strong>${db.orders.filter(o=>o.status!=='completed').length}</strong></div><div class="card"><small>Kitchen Tickets</small><strong>${db.kitchenTickets.filter(k=>k.status!=='done').length}</strong></div><div class="card"><small>Riders</small><strong>${db.riders.length}</strong></div></div><br><div class="grid cols"><div class="panel"><h2>Live Connections</h2><p>POS → Orders → Kitchen: <b>Connected</b></p><p>POS → Tables: <b>Connected</b></p><p>POS → Customers/Loyalty: <b>Connected</b></p><p>POS → Riders/Delivery: <b>Connected</b></p></div><div class="panel"><h2>Business</h2><p>${db.settings.address}</p><p>${db.settings.phone}</p><p>${db.settings.currency} · Tax ${db.settings.tax}%</p></div></div>`)}
function pos(v){v.innerHTML=shell('POS / Orders','Fast entry; completed orders create kitchen tickets automatically',`<div class="grid cols"><div class="panel"><h2>Menu</h2><div class="productgrid">${db.products.filter(p=>p.available).map(p=>`<button class="product" onclick="add('${p.id}')"><b>${p.name}</b><span>${p.category} · ${money(p.price)}</span></button>`).join('')}</div></div><div class="panel"><h2>Current Order</h2>${cart.map((x,i)=>`<div class="orderline"><span>${x.name} × ${x.qty}</span><span>${money(x.price*x.qty)} <button onclick="removeItem(${i})">×</button></span></div>`).join('')||'<p class="muted">No items yet</p>'}<div class="total"><span>Total</span><span>${money(cart.reduce((s,x)=>s+x.price*x.qty,0))}</span></div><br><button class="btn" ${cart.length?'':'disabled'} onclick="checkout()">Take Cash Payment</button></div></div>`)}
function add(id){let p=db.products.find(x=>x.id===id),x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({...p,qty:1});render()}function removeItem(i){cart.splice(i,1);render()}
async function checkout(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0),order={id:'ORD-'+Date.now(),createdAt:new Date().toISOString(),items:cart.map(({id,name,price,qty})=>({id,name,price,qty})),total,status:'new',payment:'cash'};await window.mkFoods.createOrder(order);cart=[];await load();alert('Order '+order.id+' sent to Kitchen')}
function tables(v){v.innerHTML=shell('Tables','Floor plan and table status',`<div class="grid cards">${db.tables.map(t=>`<div class="table"><b>${t.name}</b><p class="status">${t.status}</p><p class="muted">Capacity ${t.capacity}</p><button class="mini" onclick="cycleTable('${t.id}')">Change Status</button></div>`).join('')}</div>`)}
async function cycleTable(id){let t=db.tables.find(x=>x.id===id),next={Open:'Seated',Seated:'Ordered',Ordered:'Paid',Paid:'Open'}[t.status]||'Open';await window.mkFoods.updateTable(id,next);load()}
function kds(v){let active=db.kitchenTickets.filter(k=>k.status!=='done');v.innerHTML=shell('Kitchen Display','Orders from POS appear here instantly',`<div class="kitchen">${active.map(k=>`<div class="ticket"><b>${k.orderId}</b><p>${k.items.map(i=>`${i.qty} × ${i.name}`).join('<br>')}</p><span class="status">${k.status}</span><button class="mini" onclick="advanceKitchen('${k.orderId}','${k.status}')">Advance</button></div>`).join('')||'<div class="panel">No active kitchen tickets.</div>'}</div>`)}
async function advanceKitchen(id,status){let next={new:'preparing',preparing:'ready',ready:'completed'}[status]||'completed';await window.mkFoods.orderStatus(id,next);load()}
function delivery(v){v.innerHTML=shell('Delivery & Riders','Dispatch, zones, status and COD',`<div class="panel"><button class="btn" onclick="addRider()">Add Rider</button><table class="list"><tr><th>Rider</th><th>Phone</th><th>Zone</th><th>Status</th></tr>${db.riders.map(r=>`<tr><td>${r.name}</td><td>${r.phone}</td><td>${r.zone}</td><td>${r.status}</td></tr>`).join('')||'<tr><td colspan="4">No riders</td></tr>'}</table><h3>Unassigned Orders</h3>${db.orders.filter(o=>o.status==='new').map(o=>`<p>${o.id} · ${money(o.total)} ${db.riders.length?`<select onchange="assign('${o.id}',this.value)"><option value="">Assign rider</option>${db.riders.map(r=>`<option value="${r.id}">${r.name}</option>`).join('')}</select>`:'Add a rider first'}</p>`).join('')||'<p class="muted">No unassigned orders.</p>'}</div>`)}
async function assign(o,r){if(r){await window.mkFoods.assignOrder(o,r);load()}}async function addRider(){let name=prompt('Rider name');if(!name)return;let phone=prompt('Phone')||'',zone=prompt('Delivery zone')||'Bhakkar';await window.mkFoods.addRider({name,phone,zone});load()}
function customers(v){v.innerHTML=shell('Customers & Loyalty','Profiles and purchase data',`<div class="panel"><button class="btn" onclick="addCustomer()">Add Customer</button><table class="list"><tr><th>Name</th><th>Phone</th><th>Email</th><th>Points</th></tr>${db.customers.map(c=>`<tr><td>${c.name}</td><td>${c.phone}</td><td>${c.email}</td><td>${c.points}</td></tr>`).join('')||'<tr><td colspan="4">No customers yet</td></tr>'}</table></div>`)}
async function addCustomer(){let name=prompt('Customer name');if(!name)return;await window.mkFoods.addCustomer({name,phone:prompt('Phone')||'',email:prompt('Email')||'',birthday:prompt('Birthday')||''});load()}
function menu(v){v.innerHTML=shell('Menu Management','Add, edit, delete, import or export the complete menu',`<div class="panel"><div class="actions"><button class="btn" onclick="editProduct()">Add Item</button><button class="btn secondary" onclick="exportMenu()">Download CSV</button><button class="btn secondary" onclick="importMenu()">Upload CSV</button></div><p class="muted">CSV columns: id,name,category,price,available</p><table class="list"><tr><th>Item</th><th>Category</th><th>Price</th><th>Available</th><th>Actions</th></tr>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${p.available?'Yes':'No'}</td><td>${canManage()?`<button class="mini" onclick="editProduct('${p.id}')">Edit</button> <button class="mini danger" onclick="deleteProduct('${p.id}')">Delete</button>`:'Manager access required'}</td></tr>`).join('')}</table></div>`)}
async function editProduct(id=''){if(!canManage()){alert('Admin/Owner permission required');return}let p=db.products.find(x=>x.id===id)||{};let name=prompt('Item name',p.name||'');if(!name)return;let category=prompt('Category',p.category||'General')||'General';let price=prompt('Price',p.price||0);let available=confirm('Available for sale?');await window.mkFoods.saveProduct({id,name,category,price,available});load()}
async function deleteProduct(id){if(!canManage()){alert('Admin/Owner permission required');return}if(confirm('Delete this menu item?')){await window.mkFoods.deleteProduct(id);load()}}
async function exportMenu(){let p=await window.mkFoods.exportMenu();if(p)alert('Menu exported to '+p)}async function importMenu(){if(!canManage()){alert('Admin/Owner permission required');return}if(confirm('Replace the current menu with the CSV?')){let n=await window.mkFoods.importMenu();if(n!==null){await load();alert(n+' menu items imported')}}}
function inventory(v){v.innerHTML=shell('Inventory','Menu availability and stock view',`<div class="panel"><table class="list"><tr><th>Item</th><th>Category</th><th>Available</th></tr>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${p.available?'In Stock':'Sold Out'}</td></tr>`).join('')}</table></div>`)}
function suppliers(v){v.innerHTML=shell('Suppliers & Procurement','PO, receiving and AP module',`<div class="panel"><h3>Supplier workflow connected</h3><p>Use this module for vendor catalogs, purchase orders, goods receipt, barcode intake, AP and cost history.</p></div>`)}
async function printers(v){let saved=db.settings.printerMac||'Not connected';v.innerHTML=shell('Printers','Bluetooth discovery and automatic reconnect',`<div class="panel"><p>Saved printer: <b>${db.settings.printerName||saved}</b></p><button class="btn" onclick="discoverPrinters()">Discover Bluetooth Printers</button><div id="printerResults" class="printerResults"><p class="muted">Click Discover to scan paired/visible Bluetooth devices.</p></div><p class="muted">The selected MAC is saved locally and the app attempts reconnect on every restart. OS Bluetooth permissions/pairing must be enabled.</p></div>`)}
async function discoverPrinters(){let xs=await window.mkFoods.discoverPrinters();let el=document.getElementById('printerResults');el.innerHTML=xs.length?xs.map(x=>`<div class="device"><span>${x.name||'Bluetooth device'} <small>${x.mac}</small></span><button class="mini" onclick="connectPrinter('${x.mac}','${(x.name||'').replaceAll("'",'')}')">Connect</button></div>`).join(''):'<p>No Bluetooth devices discovered. Pair the printer in the OS Bluetooth settings and scan again.</p>'}
async function connectPrinter(mac,name){await window.mkFoods.updateSettings({printerMac:mac,printerName:name});await window.mkFoods.connectPrinter(mac);await load();alert('Printer saved. Auto-connect will be attempted on restart.')}
function reports(v){let sales=db.orders.reduce((s,o)=>s+o.total,0);v.innerHTML=shell('Reports & Analytics','Sales and operational reporting',`<div class="grid cards"><div class="card"><small>Orders</small><strong>${db.orders.length}</strong></div><div class="card"><small>Sales</small><strong>${money(sales)}</strong></div><div class="card"><small>Tax</small><strong>${money(sales*Number(db.settings.tax||0)/100)}</strong></div><div class="card"><small>Average Order</small><strong>${money(db.orders.length?sales/db.orders.length:0)}</strong></div></div>`)}
function history(v){v.innerHTML=shell('History','Auditable system activity',`<div class="panel"><table class="list"><tr><th>Time</th><th>Action</th><th>User/Entity</th></tr>${db.audit.slice().reverse().map(a=>`<tr><td>${new Date(a.at).toLocaleString()}</td><td>${a.action}</td><td>${a.username||a.id||a.orderId||''}</td></tr>`).join('')}</table></div>`)}
function settings(v){v.innerHTML=shell('Settings','Business and printer configuration',`<div class="panel"><label>Business<input id="business" class="field" value="${db.settings.business}"></label><label>Phone<input id="phone" class="field" value="${db.settings.phone}"></label><label>Tax %<input id="tax" class="field" value="${db.settings.tax}"></label><label>Printer Bluetooth MAC<input id="mac" class="field" value="${db.settings.printerMac||''}"></label><button class="btn" onclick="saveSettings()">Save Settings</button></div>`)}
async function saveSettings(){await window.mkFoods.updateSettings({business:business.value,phone:phone.value,tax:Number(tax.value),printerMac:mac.value});load()}
function go(x){view=x;render()}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();let r=await window.mkFoods.login(username.value,password.value);if(!r.ok){loginError.textContent='Invalid username or password';return}session=r.user;document.getElementById('login').hidden=true;document.getElementById('appRoot').hidden=false;document.getElementById('session').textContent=`${r.user.username} · ${r.user.role}`;await load()};
document.getElementById('logout').onclick=()=>{session=null;document.getElementById('appRoot').hidden=true;document.getElementById('login').hidden=false;password.value=''};
