let db={};let cart=[];let view='dashboard';
const money=n=>`Rs. ${Number(n||0).toLocaleString()}`;
async function load(){db=await window.mkFoods.snapshot();render();}
function render(){const v=document.getElementById('view');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));({dashboard:dashboard,pos:pos,tables:tables,kds:kds,delivery:delivery,customers:customers,inventory:inventory,suppliers:suppliers,reports:reports,settings:settings}[view]||dashboard)(v)}
function shell(title,sub,body,action=''){return `<div class="head"><div><h1>${title}</h1><div class="muted">${sub}</div></div>${action}</div>${body}`}
function dashboard(v){let sales=db.orders.reduce((s,o)=>s+o.total,0);v.innerHTML=shell('Dashboard','Today at MK Pizza & Ice Bar',`<div class="grid cards"><div class="card"><small>Daily Sales</small><strong>${money(sales)}</strong><span>Completed orders</span></div><div class="card"><small>Total Money Made</small><strong>${money(sales)}</strong><span>Local ledger</span></div><div class="card"><small>Active Orders</small><strong>${db.orders.filter(o=>o.status!=='completed').length}</strong><span>Open tickets</span></div><div class="card"><small>Connection</small><strong>Offline</strong><span>Transactions continue locally</span></div></div><br><div class="grid cols"><div class="panel"><h2>Quick Actions</h2><div class="actions"><button class="btn" onclick="go('pos')">New Sale</button><button class="btn secondary" onclick="go('kds')">Kitchen Display</button><button class="btn secondary" onclick="go('delivery')">Dispatch Orders</button><button class="btn secondary" onclick="go('reports')">View Reports</button></div></div><div class="panel"><h2>Business</h2><p>${db.settings.address}</p><p>${db.settings.phone}</p><p>${db.settings.currency} · Tax ${db.settings.tax}%</p></div></div>`)}
function pos(v){v.innerHTML=shell('POS / Orders','Fast touch order entry',`<div class="grid cols"><div class="panel"><h2>Menu</h2><div class="productgrid">${db.products.filter(p=>p.available).map(p=>`<button class="product" onclick="add('${p.id}')"><b>${p.name}</b><span>${p.category} · ${money(p.price)}</span></button>`).join('')}</div></div><div class="panel"><h2>Current Order</h2>${cart.length?cart.map((x,i)=>`<div class="orderline"><span>${x.name} × ${x.qty}</span><span>${money(x.price*x.qty)} <button onclick="removeItem(${i})">×</button></span></div>`).join(''):'<p class="muted">No items yet</p>'}<div class="total"><span>Total</span><span>${money(cart.reduce((s,x)=>s+x.price*x.qty,0))}</span></div><br><button class="btn" ${cart.length?'':'disabled'} onclick="checkout()">Take Payment & Complete</button></div></div>`)}
function add(id){let p=db.products.find(x=>x.id===id),x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({...p,qty:1});render()}function removeItem(i){cart.splice(i,1);render()}
async function checkout(){let total=cart.reduce((s,x)=>s+x.price*x.qty,0);let order={id:'ORD-'+Date.now(),createdAt:new Date().toISOString(),items:cart.map(({id,name,price,qty})=>({id,name,price,qty})),total,status:'completed',payment:'cash'};await window.mkFoods.createOrder(order);cart=[];await load();alert('Order saved locally: '+order.id)}
function tables(v){v.innerHTML=shell('Tables','Dining room floor plan',`<div class="grid cards">${['T1','T2','T3','T4','T5','T6','T7','T8'].map((x,i)=>`<div class="table"><b>${x}</b><p class="status">${i<2?'Ordered':'Open'}</p><p class="muted">Capacity 4</p></div>`).join('')}</div>`)}
function kds(v){let active=db.orders.filter(o=>o.status!=='completed');v.innerHTML=shell('Kitchen Display','Order routing and prep monitoring',`<div class="kitchen">${active.length?active.map(o=>`<div class="ticket"><b>${o.id}</b><p>${o.items.map(i=>`${i.qty} × ${i.name}`).join('<br>')}</p><span class="status">New</span></div>`).join(''):'<div class="panel"><h3>No active kitchen tickets</h3><p class="muted">New orders will appear here.</p></div>'}</div>`)}
function delivery(v){v.innerHTML=shell('Delivery Dispatch','Riders, zones and COD reconciliation',`<div class="panel"><button class="btn" onclick="alert('Dispatch queue ready')">Dispatch Available Orders</button><table class="list"><tr><th>Rider</th><th>Status</th><th>Zone</th><th>COD</th></tr><tr><td>Available Rider</td><td><span class="status">Available</span></td><td>Bhakkar</td><td>${money(0)}</td></tr></table></div>`)}
function customers(v){v.innerHTML=shell('Customers & Loyalty','Profiles, purchase history and rewards',`<div class="panel"><button class="btn" onclick="alert('Customer creation is ready for the local store layer')">Add Customer</button><table class="list"><tr><th>Name</th><th>Phone</th><th>Purchases</th><th>Rewards</th></tr>${db.customers.length?db.customers.map(c=>`<tr><td>${c.name}</td><td>${c.phone}</td><td>${c.purchases||0}</td><td>${c.points||0} pts</td></tr>`).join(''):'<tr><td colspan="4">No customers yet</td></tr>'}</table></div>`)}
function inventory(v){v.innerHTML=shell('Inventory','Stock and availability',`<div class="panel"><table class="list"><tr><th>Item</th><th>Category</th><th>Availability</th></tr>${db.products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td><span class="status">${p.available?'In Stock':'Sold Out'}</span></td></tr>`).join('')}</table></div>`)}
function suppliers(v){v.innerHTML=shell('Suppliers & Procurement','Vendors, purchase orders and accounts payable',`<div class="panel"><button class="btn" onclick="alert('Purchase order workflow')">New Purchase Order</button><p class="muted">Supplier catalog, goods receiving, barcode intake and AP are managed from the procurement module.</p></div>`)}
function reports(v){let sales=db.orders.reduce((s,o)=>s+o.total,0);v.innerHTML=shell('Reports & Analytics','Sales, profit and operational reporting',`<div class="grid cards"><div class="card"><small>Orders</small><strong>${db.orders.length}</strong></div><div class="card"><small>Sales</small><strong>${money(sales)}</strong></div><div class="card"><small>Tax</small><strong>${money(sales*Number(db.settings.tax||0)/100)}</strong></div><div class="card"><small>Average Order</small><strong>${money(db.orders.length?sales/db.orders.length:0)}</strong></div></div><br><div class="panel"><h2>Transactions</h2><table class="list"><tr><th>Order</th><th>Date</th><th>Payment</th><th>Total</th></tr>${db.orders.slice().reverse().map(o=>`<tr><td>${o.id}</td><td>${new Date(o.createdAt).toLocaleString()}</td><td>${o.payment}</td><td>${money(o.total)}</td></tr>`).join('')}</table></div>`)}
function settings(v){v.innerHTML=shell('Settings','Business, tax and printer configuration',`<div class="panel"><label>Business<input id="business" class="field" value="${db.settings.business}"></label><label>Phone<input id="phone" class="field" value="${db.settings.phone}"></label><label>Printer Bluetooth MAC<input id="mac" class="field" value="${db.settings.printerMac||''}" placeholder="AA:BB:CC:DD:EE:FF"></label><button class="btn" onclick="saveSettings()">Save Settings</button></div>`)}
async function saveSettings(){await window.mkFoods.updateSettings({business:business.value,phone:phone.value,printerMac:mac.value});await load();alert('Settings saved locally')}
function go(x){view=x;render()}document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));load();
