(() => {
'use strict';
const KEY='mkfoods.final.v3';
const defaults={schema:3,recipes:{},ingredients:{},modifierGroups:{},variants:{},payments:{},credit:{},shifts:{},branches:{},promotions:{},stations:{},printerRules:{},reservations:{},deliveryZones:{},audit:[],sync:{queue:[],acked:0},notifications:[]};
const clone=x=>JSON.parse(JSON.stringify(x));
const read=()=>{try{return Object.assign(clone(defaults),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){return clone(defaults)}};
let s=read(); const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
const id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const user=()=>window.session?.username||window.currentUser?.username||'system';
const role=()=>window.session?.role||window.currentUser?.role||'Cashier';
const manager=()=>['Admin','Owner','Manager'].includes(role());
const now=()=>new Date().toISOString();
const audit=(action,data={})=>{s.audit.unshift({id:id('AUD'),action,by:user(),at:now(),...data});s.audit=s.audit.slice(0,2000);save()};
const notify=(type,message)=>{s.notifications.unshift({id:id('NTF'),type,message,at:now(),read:false});s.notifications=s.notifications.slice(0,500);save()};
const approve=action=>{if(manager())return true;const pin=prompt(`Manager approval PIN required: ${action}`);if(!pin)return false;audit('APPROVAL_GRANTED',{action,method:'PIN'});return true};
const states={draft:['held','confirmed','cancelled'],held:['draft','confirmed','cancelled'],confirmed:['sent_to_kitchen','cancelled','voided'],sent_to_kitchen:['preparing','held','voided'],preparing:['ready','held','voided'],ready:['collecting','dispatching','completed'],collecting:['completed'],dispatching:['out_for_delivery','completed'],out_for_delivery:['completed','returned'],completed:['refunded','reopened'],reopened:['confirmed','cancelled'],returned:[],cancelled:[],voided:[],refunded:[]};
function transition(order,next,reason=''){const cur=order.status==='new'?'draft':(order.status||'draft');if(!(states[cur]||[]).includes(next))throw Error(`INVALID_TRANSITION:${cur}->${next}`);if(['voided','refunded','reopened'].includes(next)&&!approve(next.toUpperCase()))throw Error('APPROVAL_REQUIRED');order.status=next;order.statusAt=now();order.statusReason=reason;audit('ORDER_TRANSITION',{orderId:order.id,from:cur,to:next,reason});return order}
function unitFactor(from,to){if(from===to)return 1;const m={mg:.001,g:1,kg:1000,ml:1,l:1000,each:1,box:1};if(m[from]!=null&&m[to]!=null)return m[from]/m[to];throw Error(`UNIT_CONVERSION_UNSUPPORTED:${from}->${to}`)}
function recipeCost(productId){return(s.recipes[productId]||[]).reduce((sum,l)=>{const i=s.ingredients[l.ingredientId];if(!i)return sum;return sum+Number(l.qty||0)*unitFactor(l.unit||i.unit||'each',i.costUnit||i.unit||'each')*Number(i.costPerUnit||0)},0)}
function consumeRecipe(productId,multiplier=1){for(const l of s.recipes[productId]||[]){const i=s.ingredients[l.ingredientId];if(!i)continue;const q=Number(l.qty||0)*Number(multiplier||0)*unitFactor(l.unit||i.unit||'each',i.unit||'each');i.stock=Math.max(0,Number(i.stock||0)-q);if(i.stock<=Number(i.minStock||0))notify('low-stock',`${i.name||l.ingredientId} is below minimum stock`)}save()}
function addPayment(orderId,method,amount,reference=''){const a=Number(amount||0);if(a<=0)throw Error('PAYMENT_AMOUNT_REQUIRED');const o=(window.db?.orders||[]).find(x=>x.id===orderId);if(!o)throw Error('ORDER_NOT_FOUND');s.payments[orderId] ||= [];const paid=s.payments[orderId].reduce((n,p)=>n+Number(p.amount||0),0);const due=Math.max(0,Number(o.total||0)-paid);if(a>due+.005)throw Error('PAYMENT_EXCEEDS_DUE');s.payments[orderId].push({id:id('PAY'),method,amount:a,reference,at:now(),by:user()});const total=paid+a;o.paymentStatus=total+.005>=Number(o.total||0)?'paid':'partial';o.amountPaid=total;o.amountDue=Math.max(0,Number(o.total||0)-total);audit('PAYMENT_RECORDED',{orderId,method,amount:a,remaining:o.amountDue});save();return{paid:total,due:o.amountDue,status:o.paymentStatus}}
function credit(orderId,customerId,amount){const a=Number(amount||0);if(a<=0)throw Error('CREDIT_AMOUNT_REQUIRED');if(!customerId)throw Error('CUSTOMER_REQUIRED');s.credit[customerId] ||= {balance:0,ledger:[]};s.credit[customerId].balance+=a;s.credit[customerId].ledger.push({id:id('CR'),orderId,amount:a,type:'credit',at:now()});audit('CUSTOMER_CREDIT',{orderId,customerId,amount:a});save();return s.credit[customerId]}
function settleCredit(customerId,amount){if(!approve('CREDIT_SETTLEMENT'))throw Error('APPROVAL_REQUIRED');const a=Number(amount||0),c=s.credit[customerId];if(!c||a<=0||a>c.balance)throw Error('INVALID_CREDIT_SETTLEMENT');c.balance-=a;c.ledger.push({id:id('CRP'),amount:a,type:'payment',at:now(),by:user()});audit('CUSTOMER_CREDIT_SETTLED',{customerId,amount:a});save();return c}
function startShift(cashier,openingCash){if(s.shifts[cashier]?.status==='open')throw Error('SHIFT_ALREADY_OPEN');s.shifts[cashier]={id:id('SHIFT'),cashier,openingCash:Number(openingCash||0),cashIn:0,cashOut:0,refunds:0,status:'open',openedAt:now()};audit('SHIFT_OPENED',{cashier,openingCash});save();return s.shifts[cashier]}
function shiftEntry(cashier,type,amount,reason=''){const sh=s.shifts[cashier];if(!sh||sh.status!=='open')throw Error('SHIFT_NOT_OPEN');const a=Number(amount||0);if(a<=0)throw Error('AMOUNT_REQUIRED');if(type==='cashIn')sh.cashIn+=a;else if(type==='cashOut')sh.cashOut+=a;else if(type==='refund')sh.refunds+=a;else throw Error('UNKNOWN_SHIFT_ENTRY');sh.entries ||= [];sh.entries.push({id:id('SHIFT-E'),type,amount:a,reason,at:now(),by:user()});save();return sh}
function closeShift(cashier,actualCash){const sh=s.shifts[cashier];if(!sh||sh.status!=='open')throw Error('SHIFT_NOT_OPEN');const expected=Number(sh.openingCash||0)+Number(sh.cashIn||0)-Number(sh.cashOut||0)-Number(sh.refunds||0);const actual=Number(actualCash||0);sh.expectedCash=expected;sh.actualCash=actual;sh.variance=expected-actual;sh.closedAt=now();sh.status='closed';audit('SHIFT_CLOSED',{cashier,expected,actual,variance:sh.variance});save();return sh}
function calculatePromotion(order,promo){const subtotal=Number(order.subtotal||0);if(subtotal<Number(promo.minOrder||0))return subtotal;switch(promo.type){case'percent':return subtotal*(1-Math.min(100,Number(promo.value||0))/100);case'fixed':return Math.max(0,subtotal-Number(promo.value||0));case'bogo':{const eligible=(order.items||[]).filter(i=>!promo.productId||i.id===promo.productId);const qty=eligible.reduce((n,i)=>n+Number(i.qty||0),0);return Math.max(0,subtotal-Math.floor(qty/2)*Number(promo.freePrice||0))}case'combo':return promo.price!=null?Math.min(subtotal,Number(promo.price)):subtotal;default:return subtotal}}
function applyPromotions(order,date=new Date()){const day=date.getDay(),mins=date.getHours()*60+date.getMinutes();let best=Number(order.subtotal||0),applied=null;for(const p of Object.values(s.promotions)){if(p.active===false||p.days&&!p.days.includes(day)||best<Number(p.minOrder||0))continue;const[a,b]=(p.start||'00:00').split(':').map(Number),[c,d]=(p.end||'23:59').split(':').map(Number);if(mins<a*60+b||mins>c*60+d)continue;const v=calculatePromotion(order,p);if(v<best){best=v;applied=p}}return{discount:Number(order.subtotal||0)-best,total:best,promotion:applied}}
function routeItem(item){const cat=String(item.category||'').toLowerCase();return item.station||s.stations[item.category]||(/drink|bar|shake/.test(cat)?'Bar':/dessert|ice/.test(cat)?'Dessert':/fry|side/.test(cat)?'Fry':/grill|burger/.test(cat)?'Grill':'Kitchen')}
function printPlan(order){const groups={};for(const i of order.items||[]){const st=routeItem(i);(groups[st] ||= []).push(i)}return Object.entries(groups).map(([station,items])=>({station,items,printer:s.printerRules[station]||s.printerRules.default||null}))}
function reserve(x){if(!x.tableId||!x.dateTime)throw Error('TABLE_RESERVATION_REQUIRED');const r={id:id('RES'),status:'reserved',createdAt:now(),...x};s.reservations[r.id]=r;audit('TABLE_RESERVED',{tableId:r.tableId,dateTime:r.dateTime});save();return r}
function transferTable(from,to,orderId){const tables=window.db?.tables||[];const a=tables.find(x=>x.id===from),b=tables.find(x=>x.id===to);if(!a||!b)throw Error('TABLE_NOT_FOUND');if(b.status==='Occupied')throw Error('TARGET_TABLE_OCCUPIED');const o=(window.db?.orders||[]).find(x=>x.id===orderId);if(!o)throw Error('ORDER_NOT_FOUND');o.tableId=to;a.status='Open';b.status='Occupied';audit('TABLE_TRANSFER',{from,to,orderId});return o}
function branch(id,name){if(!approve('BRANCH_CHANGE'))throw Error('MANAGER_APPROVAL_REQUIRED');s.branches[id] ||= {id,name,active:true,menu:[],printers:[],staff:[]};s.branches[id].name=name||s.branches[id].name;save();return s.branches[id]}
function queueSync(type,payload){const e={eventId:id('EVT'),originDeviceId:localStorage.getItem('mkfoods.deviceId')||id('DEV'),type,payload,createdAt:now()};localStorage.setItem('mkfoods.deviceId',e.originDeviceId);s.sync.queue.push(e);s.sync.queue=s.sync.queue.slice(-5000);save();return e}
function ackSync(eventId){s.sync.queue=s.sync.queue.filter(x=>x.eventId!==eventId);s.sync.acked++;save()}
function backup(){const payload={schema:3,createdAt:now(),db:clone(window.db||{}),final:clone(s)};const text=JSON.stringify(payload);let h=0;for(let i=0;i<text.length;i++)h=((h<<5)-h+text.charCodeAt(i))|0;payload.checksum=String(h>>>0);audit('BACKUP_CREATED',{checksum:payload.checksum});return payload}
function verifyBackup(p){if(!p||p.schema!==3||!p.db||!p.final||!p.checksum)return false;const q=clone(p),expected=q.checksum;delete q.checksum;const text=JSON.stringify(q);let h=0;for(let i=0;i<text.length;i++)h=((h<<5)-h+text.charCodeAt(i))|0;return String(h>>>0)===String(expected)}
window.mkFinal={state:()=>clone(s),transition,unitFactor,recipeCost,consumeRecipe,addPayment,credit,settleCredit,startShift,shiftEntry,closeShift,calculatePromotion,applyPromotions,routeItem,printPlan,reserve,transferTable,branch,queueSync,ackSync,backup,verifyBackup,audit,notify};
const oldCreate=window.mkFoods?.createOrder;if(oldCreate&&!oldCreate.__finalWrapped){const wrapped=async o=>{const result=await oldCreate(o);if(result?.ok===false)return result;for(const i of o.items||[])consumeRecipe(i.id,Number(i.qty||0));queueSync('ORDER_CREATED',{orderId:o.id});return result};wrapped.__finalWrapped=true;window.mkFoods.createOrder=wrapped}
save();
})();
