(() => {
  const e = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let bluetoothDevice = null, bluetoothServer = null, bluetoothCharacteristic = null, serialPort = null, serialWriter = null;
  const BLE_SERVICE_CANDIDATES = ['000018f0-0000-1000-8000-00805f9b34fb','49535343-fe7d-4ae5-8fa9-9fafd205e455'];
  const BLE_CHARACTERISTIC_CANDIDATES = ['00002af1-0000-1000-8000-00805f9b34fb','49535343-8841-43f4-a8d4-ecbe34729bb3','49535343-1e4d-4bd9-ba61-23c647249616'];
  const bluetoothSupported = () => !!navigator.bluetooth; const serialSupported = () => !!navigator.serial;
  async function findWritableCharacteristic(server){for(const serviceId of BLE_SERVICE_CANDIDATES)try{const service=await server.getPrimaryService(serviceId);for(const characteristicId of BLE_CHARACTERISTIC_CANDIDATES)try{const c=await service.getCharacteristic(characteristicId);if(c.properties.write||c.properties.writeWithoutResponse)return c}catch(_){}const chars=await service.getCharacteristics(),c=chars.find(x=>x.properties.write||x.properties.writeWithoutResponse);if(c)return c}catch(_){}for(const service of await server.getPrimaryServices()){const c=(await service.getCharacteristics()).find(x=>x.properties.write||x.properties.writeWithoutResponse);if(c)return c}throw new Error('No writable Bluetooth printer characteristic was found.')}
  function toast(message,error=false){let box=document.getElementById('printerToast');if(!box){box=document.createElement('div');box.id='printerToast';box.className='workflow-toast';document.body.appendChild(box)}box.textContent=message;box.className=`workflow-toast ${error?'error':'success'}`;box.hidden=false;clearTimeout(box._timer);box._timer=setTimeout(()=>box.hidden=true,3500)}
  async function connectBluetooth(){if(!bluetoothSupported())throw new Error('Bluetooth LE is not available in this Windows WebView.');bluetoothDevice=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:BLE_SERVICE_CANDIDATES});bluetoothDevice.addEventListener('gattserverdisconnected',()=>{bluetoothServer=null;bluetoothCharacteristic=null;renderBluetoothState()});bluetoothServer=await bluetoothDevice.gatt.connect();bluetoothCharacteristic=await findWritableCharacteristic(bluetoothServer);await window.mkFoods.updateSettings({printerName:bluetoothDevice.name||'Bluetooth Printer',printerMac:bluetoothDevice.id||'',printerConnection:'bluetooth-le',receiptPrinter:bluetoothDevice.name||'Bluetooth Printer'});await load();renderBluetoothState();toast('Bluetooth printer connected and assigned to Receipts.')}
  async function reconnectKnownBluetooth(){if(!navigator.bluetooth?.getDevices)return;try{const devices=await navigator.bluetooth.getDevices();const d=devices.find(x=>x.name&&x.name===(db.settings?.printerName||''));if(!d)return;bluetoothDevice=d;bluetoothDevice.addEventListener('gattserverdisconnected',()=>{bluetoothServer=null;bluetoothCharacteristic=null;renderBluetoothState()});bluetoothServer=await d.gatt.connect();bluetoothCharacteristic=await findWritableCharacteristic(bluetoothServer);renderBluetoothState()}catch(_){} }
  async function connectSerial(){if(!serialSupported())throw new Error('Web Serial is not available in this Windows WebView.');serialPort=await navigator.serial.requestPort();await serialPort.open({baudRate:9600});serialWriter=serialPort.writable?.getWriter();await window.mkFoods.updateSettings({printerName:'Bluetooth / COM Printer',printerMac:'',printerConnection:'serial',receiptPrinter:'Bluetooth / COM Printer'});await load();renderBluetoothState();toast('COM printer connected and assigned to Receipts.')}
  async function disconnectBluetooth(){try{bluetoothDevice?.gatt?.disconnect()}catch(_){}bluetoothDevice=null;bluetoothServer=null;bluetoothCharacteristic=null;try{serialWriter?.releaseLock()}catch(_){}serialWriter=null;try{await serialPort?.close()}catch(_){}serialPort=null;renderBluetoothState();toast('Printer connection closed.')}
  async function sendRaw(data){const bytes=data instanceof Uint8Array?data:new Uint8Array(data);if(bluetoothCharacteristic){for(let i=0;i<bytes.length;i+=180){const c=bytes.slice(i,i+180);if(bluetoothCharacteristic.properties.writeWithoutResponse)await bluetoothCharacteristic.writeValueWithoutResponse(c);else await bluetoothCharacteristic.writeValue(c)}return true}if(serialWriter){await serialWriter.write(bytes);return true}throw new Error('Connect a Bluetooth / COM printer first.')}
  async function testBluetoothPrint(){const data=new TextEncoder().encode('\x1b@MK FOODS POS\nPrinter connection test\n\x1b\x64\x04\x1dV\x42\x14');await sendRaw(data)}
  function renderBluetoothState(){const box=document.getElementById('bluetoothState');if(!box)return;const connected=!!bluetoothCharacteristic||!!serialWriter,saved=db.settings?.printerConnection==='bluetooth-le'||db.settings?.printerConnection==='serial';box.innerHTML=connected?`<div class="notice"><b>Live thermal connection</b><br><span class="muted">${e(bluetoothDevice?.name||'Bluetooth / COM printer')}</span><div class="toolbar" style="margin-top:10px"><button class="mini" onclick="testBluetoothPrint()">Test Print</button><button class="mini secondary" onclick="disconnectBluetooth()">Disconnect</button></div></div>`:saved?`<div class="notice"><b>Saved printer</b><br><span class="muted">${e(db.settings?.printerName||'Bluetooth / COM printer')} · ${e(db.settings?.printerConnection||'saved')}</span><div class="toolbar" style="margin-top:10px"><button class="mini" onclick="reconnectSavedPrinter()">Reconnect</button></div></div>`:'<div class="notice">No live Bluetooth / COM connection.</div>'}
  window.connectBluetooth=async()=>{try{await connectBluetooth()}catch(err){toast(err?.message||String(err),true)}};window.connectBluetoothSerial=async()=>{try{await connectSerial()}catch(err){toast(err?.message||String(err),true)}};window.reconnectSavedPrinter=async()=>{await reconnectKnownBluetooth();if(!bluetoothCharacteristic&&!serialWriter)toast('Saved Bluetooth device is not currently available. Use Discover Bluetooth.',true);else toast('Saved Bluetooth printer reconnected.')};window.disconnectBluetooth=disconnectBluetooth;window.testBluetoothPrint=async()=>{try{await testBluetoothPrint();toast('Test print sent.')}catch(err){toast(err?.message||String(err),true)}};window.printThermalBytes=sendRaw;
  window.refreshPrinters=async()=>{const box=document.getElementById('printerList');if(box)box.innerHTML='<p class="muted">Scanning installed Windows printers…</p>';const r=await window.mkFoods.discoverPrinters();if(r?.ok===false){if(box)box.innerHTML=`<div class="notice">Could not read Windows printers: ${e(r.reason)}</div>`;return}const selected=db.settings?.printerName||'',printers=Array.isArray(r)?r:[];if(box)box.innerHTML=printers.length?printers.map(p=>`<div class="dispatch"><div><b>${e(p.name)}</b><div class="muted">${p.default?'Windows default printer':'Installed printer'} · Status ${e(p.status)}</div></div><button class="mini ${selected===p.name?'secondary':''}" onclick="selectPrinter('${e(p.name).replace(/'/g,'&#39;')}')">${selected===p.name?'Selected':'Select'}</button></div>`).join(''):'<div class="notice">No installed Windows printers were found.</div>'};
  window.selectPrinter=async name=>{const r=await window.mkFoods.connectPrinter(name);if(r?.ok===false){toast(r.reason||'Could not select printer.',true);return}await load();go('printers');toast(`${name} selected for receipts.`)};
  window.setPrinterProfile=async(profile,name)=>{const key={receipt:'receiptPrinter',kitchen:'kitchenPrinter',expo:'expoPrinter',delivery:'deliveryPrinter'}[profile];if(!key)return;const r=await window.mkFoods.updateSettings({[key]:name});if(r?.ok===false){toast(r.reason||'Could not save printer profile.',true);return}await load();go('printers');toast(`${profile} printer assigned.`)};
  views.printers=v=>{const selected=db.settings?.printerName||'',profiles=[['receipt','Receipt',db.settings?.receiptPrinter||selected],['kitchen','Kitchen / KOT',db.settings?.kitchenPrinter||''],['expo','Expo / Handoff',db.settings?.expoPrinter||''],['delivery','Delivery / Packing',db.settings?.deliveryPrinter||'']];v.innerHTML=shell('Printer Connections','Thermal-first setup · direct Windows RAW · Bluetooth/COM · printer profiles',`<div class="grid cols"><div class="panel"><div class="toolbar"><div><h2>Installed Windows Printers</h2><p class="muted">Scanning runs silently in the background; no CMD or PowerShell window is shown.</p></div><button class="btn" onclick="refreshPrinters()">Scan</button></div><div id="printerList"><div class="notice">Press Scan to load Windows printers.</div></div></div><div class="panel"><h2>Bluetooth / COM Thermal</h2><p class="muted">Connect once. The saved device can be reconnected without re-entering setup.</p><div class="toolbar"><button class="btn" onclick="connectBluetooth()">Discover Bluetooth</button><button class="btn secondary" onclick="connectBluetoothSerial()">Connect COM</button></div><div id="bluetoothState" style="margin-top:12px"></div></div><div class="panel"><h2>Printer Profiles</h2><p class="muted">Route receipts and kitchen work to different stations, like modern restaurant POS systems.</p>${profiles.map(([k,label,val])=>`<label class="profile-row"><span><b>${label}</b><small>${val?e(val):'Not assigned'}</small></span><select class="field" onchange="setPrinterProfile('${k}',this.value)"><option value="">Choose printer…</option>${(db.settings?.availablePrinters||[]).map(n=>`<option ${n===val?'selected':''}>${e(n)}</option>`).join('')}</select></label>`).join('')}<p class="muted" style="margin-top:10px">Scan Windows printers to populate profile choices.</p></div><div class="panel"><h2>Active Receipt Printer</h2><div class="notice">${selected?`<b>${e(selected)}</b><br><span class="muted">Receipt profile: ${e(db.settings?.receiptPrinter||selected)}</span>`:'No printer selected yet.'}</div></div></div>`);renderBluetoothState();reconnectKnownBluetooth()};
})();