(() => {
  'use strict';
  const n=v=>Math.max(0,Number(v||0));
  const clean=s=>String(s??'').replace(/[\r\n]+/g,' ').trim();
  const line=(label,value,w=42)=>{const a=clean(label),b=clean(value),spaces=Math.max(1,w-a.length-b.length);return a+' '.repeat(spaces)+b+'\n'};
  const center=(s,w=42)=>{s=clean(s);const left=Math.max(0,Math.floor((w-s.length)/2));return ' '.repeat(left)+s+'\n'};
  const moneyText=v=>`${db?.settings?.currency||'Rs.'} ${n(v).toLocaleString(undefined,{maximumFractionDigits:2})}`;
  const normalizeMac=value=>{const hex=String(value||'').replace(/[^0-9a-f]/gi,'').toUpperCase();return hex.length===12?hex.match(/.{2}/g).join(':'):''};
  const printerRoute=()=>{const s=db?.settings||{},connection=String(s.printerConnection||'windows-raw').toLowerCase();if(connection==='bluetooth-spp'){const mac=normalizeMac(s.printerMac);if(mac)return `__BLUETOOTH_RAW__|${mac}`}if(connection==='bluetooth-com'&&/^COM\d+$/i.test(String(s.printerComPort||'').trim()))return `__BLUETOOTH_COM__|${String(s.printerComPort).trim().toUpperCase()}`;if(connection==='network-raw'&&String(s.printerIp||'').trim())return `__NETWORK_RAW__|${String(s.printerIp).trim()}:${Number(s.printerPort||9100)||9100}`;return s.receiptPrinter||s.printerName||''};
  const sendRaw=async(bytes,route=printerRoute())=>{if(!route)throw Error('No printer route is configured.');if(!window.mkFoods?.printThermal)throw Error('Thermal printing backend is unavailable.');const r=await window.mkFoods.printThermal(route,bytes);if(r?.ok===false)throw Error(r.reason||'Print failed');return r};
  window.discoverPrinters=async()=>{try{if(!window.mkFoods?.printThermal)return[];const r=await window.mkFoods.printThermal('__DISCOVER__',new Uint8Array()),printers=Array.isArray(r?.printers)?r.printers:[];window.mkFoodsPrinters=printers;return printers}catch(e){console.error('Printer discovery failed',e);window.mkFoodsPrinters=[];return[]}};
  const populatePrinterSelects=printers=>{const selects=[...document.querySelectorAll('select')].filter(el=>`${el.id} ${el.name} ${el.dataset?.setting||''}`.toLowerCase().includes('printer'));for(const select of selects){const current=select.value||db?.settings?.printerName||'';select.innerHTML='';const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=printers.length?'Select printer…':'No Windows printers found';select.appendChild(placeholder);for(const p of printers){const option=document.createElement('option');option.value=p.name;option.textContent=`${p.name} — ${p.status}`;option.dataset.connection=p.connection||'windows-raw';option.dataset.online=p.online?'true':'false';select.appendChild(option)}if([...select.options].some(o=>o.value===current))select.value=current}};
  window.refreshPrinterDiscovery=async()=>{const printers=await window.discoverPrinters();populatePrinterSelects(printers);return printers};
  window.printRawDocument=async(document={})=>{const W=Number(db?.settings?.receiptWidth||42)>=48?48:42;let out='\x1b@'+center(document.title||db?.settings?.business||'MK FOODS POS',W);if(document.subtitle)out+=center(document.subtitle,W);out+='-'.repeat(W)+'\n';for(const row of Array.isArray(document.lines)?document.lines:[])out+=Array.isArray(row)?line(row[0],row[1],W):clean(row)+'\n';out+='-'.repeat(W)+'\n'+center(db?.settings?.receiptFooter||'Thank you for visiting!',W)+'\n\n\n\x1dV\x42\x00';return sendRaw(new TextEncoder().encode(out),document.route||printerRoute())};
  window.printReceipt=async order=>{try{const s=db?.settings||{},route=printerRoute();if(!route)return window.mkFoodsUX?.toast('Select a receipt printer first.');const W=Number(s.receiptWidth||42)>=48?48:42;let out='\x1b@\x1bE\x01'+center(s.business||'MK FOODS POS',W)+'\x1bE\x00';if(s.address)out+=center(s.address,W);if(s.phone)out+=center(s.phone,W);if(s.taxNumber)out+=center(`${s.taxLabel||'Tax'} No: ${s.taxNumber}`,W);out+='-'.repeat(W)+'\n'+line('Order',order?.id||'-',W)+line('Date',new Date(order?.createdAt||Date.now()).toLocaleString(),W);if(order?.cashCollectedBy)out+=line('Cashier',order.cashCollectedBy,W);if(order?.customerName)out+=line('Customer',order.customerName,W);out+='-'.repeat(W)+'\n';for(const i of Array.isArray(order?.items)?order.items:[]){const qty=n(i.qty),total=moneyText(n(i.price)*qty),prefix=`${qty} x `,name=clean(i.name||i.id||'Item'),avail=Math.max(1,W-prefix.length-total.length-1),shown=name.slice(0,avail);out+=prefix+shown+' '.repeat(Math.max(1,W-prefix.length-shown.length-total.length))+total+'\n';if(i.note)out+='  Note: '+clean(i.note).slice(0,W-8)+'\n'}out+='-'.repeat(W)+'\n'+line('Subtotal',moneyText(order?.subtotal),W);if(n(order?.discount))out+=line('Discount','-'+moneyText(order.discount),W);if(n(order?.tax))out+=line(s.taxLabel||'Tax',moneyText(order.tax),W);if(n(order?.deliveryFee))out+=line('Delivery',moneyText(order.deliveryFee),W);out+='-'.repeat(W)+'\n\x1bE\x01'+line('TOTAL',moneyText(order?.total),W)+'\x1bE\x00'+'-'.repeat(W)+'\n'+line('Payment',order?.payment||'-',W);if(order?.paymentStatus)out+=line('Status',order.paymentStatus,W);out+='\n'+center(s.receiptFooter||'Thank you for visiting!',W)+'\n\n\n\x1dV\x42\x00';await sendRaw(new TextEncoder().encode(out),route);window.mkFoodsUX?.toast(`Receipt sent to ${s.printerName||route}`)}catch(e){console.error(e);window.mkFoodsUX?.toast(`Receipt failed: ${e.message||e}`,true)}};
  window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>window.refreshPrinterDiscovery?.(),700));
})();
