(() => {
  'use strict';
  const KEY='mkfoods.order.workflow.v2';
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>`${window.db?.settings?.currency||'Rs.'} ${Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2})}`;
  const staff=()=>Array.isArray(window.db?.staff)?window.db.staff.filter(x=>x.active!==false):[];
  const find=id=>(window.db?.orders||[]).find(x=>x.id===id);
  const waiter=()=>document.getElementById('workflowWaiter')?.value||'';
  const syncAudit=()=>{if(!window.db)return;const state=read();const audit=Array.isArray(window.db.audit)?window.db.audit:(window.db.audit=[]);const seen=new Set(audit.map(x=>`${x.orderId||x.id}|${x.at}|${x.action}`));Object.values(state.orders||{}).forEach(w=>(w.events||[]).forEach(e=>{const k=`${w.orderId}|${e.at}|${e.action}`;if(!seen.has(k)){audit.push({id:`wf-${w.orderId}-${e.at}-${e.action}`,orderId:w.orderId,at:e.at,action:e.action,username:e.user||'system',source:'workflow',...e});seen.add(k)}}))};
  const addWaiterField=()=>{const root=document.getElementById('view');if(!root||document.getElementById('workflowWaiter'))return;const type=document.getElementById('orderType');if(!type)return;const host=type.closest('label')?.parentElement||type.parentElement;if(!host)return;const options=staff().map(x=>`<option value="${esc(x.username)}">${esc(x.name||x.username)}</option>`).join('');const box=document.createElement('label');box.className='workflow-waiter-field';box.innerHTML=`<span>Waiter / Table Person</span><select id="workflowWaiter" class="field"><option value="">Select waiter...</option>${options}</select><small>Required for dine-in orders</small>`;host.appendChild(box);try{const last=localStorage.getItem('mkfoods.last.waiter');if(last)box.querySelector('select').value=last}catch(_) {}};
  const patchCreateOrder=()=>{const api=window.mkFoods;if(!api||typeof api.createOrder!=='function'||api.__waiterPatched)return;const original=api.createOrder;api.createOrder=async function(payload,...rest){const w=waiter();const type=document.getElementById('orderType')?.value||payload?.orderType;if(w)payload={...payload,waiterId:w,waiterUsername:w,tablePerson:w};return original.call(this,payload,...rest)};api.__waiterPatched=true};
  const patchCollect=()=>{if(typeof window.collectOrder!=='function'||window.__waiterWorkflowPatched)return;const original=window.collectOrder;window.collectOrder=async function(...args){const type=document.getElementById('orderType')?.value||'Takeaway';const w=waiter();if(type==='Dine-in'&&!w){window.showToast?.('Select the waiter / table person first.','error');return}try{if(w)localStorage.setItem('mkfoods.last.waiter',w)}catch(_){}return original.apply(this,args)};window.__waiterWorkflowPatched=true};
  const old=window.showOrderTracking;
  window.showOrderTracking=id=>{syncAudit();const o=find(id),a=(window.db?.audit||[]).filter(x=>x.id===id||x.orderId===id),local=read().orders?.[id],events=[...(local?.events||[]),...a.map(x=>({at:x.at,action:x.action,user:x.username||x.createdBy||x.user||'-'}))].sort((x,y)=>new Date(x.at)-new Date(y.at));if(!o){old?.(id);return}const unique=[];const seen=new Set;events.forEach(e=>{const k=`${e.at}|${e.action}|${e.user}`;if(!seen.has(k)){seen.add(k);unique.push(e)}});const timeline=unique.map(e=>`<div class="timeline-item"><span class="timeline-dot"></span><div><b>${esc(String(e.action||'EVENT').replaceAll('_',' '))}</b><div class="muted">${esc(e.user)} · ${e.at?new Date(e.at).toLocaleString():'-'}</div></div></div>`).join('');const html=`<div class="tracking-hero"><div><span class="muted">${esc(o.orderType||'Order')}</span><h2>${esc(o.customerName||'Walk-in')}</h2></div><div class="tracking-total">${money(o.total)}</div></div><div class="detail-grid"><div class="detail-kv"><span>Waiter / Table Person</span><b>${esc(o.waiterUsername||o.waiterId||o.tablePerson||o.collectedBy||'-')}</b></div><div class="detail-kv"><span>Counter</span><b>${esc(o.counterBy||'-')}</b></div><div class="detail-kv"><span>Prepared</span><b>${esc(o.preparedBy||'-')}</b></div><div class="detail-kv"><span>Cashier</span><b>${esc(o.cashCollectedBy||'-')}</b></div></div><h3>Complete audit trail</h3><div class="workflow-timeline">${timeline||'<span class="muted">No audit events recorded.</span>'}</div><h3>Items</h3><table class="data"><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>${(o.items||[]).map(i=>`<tr><td>${esc(i.name||i.id)}</td><td>${i.qty||0}</td><td>${money((i.price||0)*(i.qty||0))}</td></tr>`).join('')}</tbody></table>`;if(typeof openDetail==='function')openDetail(`Order Tracking · ${id}`,html)};
  window.MKWorkflowAudit={sync:syncAudit,install:()=>{syncAudit();addWaiterField();patchCreateOrder();patchCollect()}};
  const install=()=>{syncAudit();addWaiterField();patchCreateOrder();patchCollect()};install();setInterval(()=>{syncAudit();if(document.visibilityState!=='hidden'){addWaiterField();patchCreateOrder();patchCollect()}},2500);
})();
